flakes: remove experimental repl-flake
NixOS/nix pull request #10299
Opened 2024-03-23 01:35 UTC by detroyejr

# Motivation

This PR removes the repl-flake feature that was adopted to provide a migration path when changing the behavior of `nix repl`.  Moving forward this command will behave more like the rest of the modern cli.

```
# No longer evaluates and returns the same error as nix run
nix repl default.nix

>>> error: path 'default.nix' is not a flake (because it's not a directory)

# Works as before
nix repl --file default.nix
```

# Context

Fixes https://github.com/NixOS/nix/issues/10103

No major changes from a code perspective. I only removed a small amount. `applyDefaultInstallables` still plays a part in allowing `nix repl` to run without any arguments so it's not removed entirely. 

Tests all pass but it would probably be good to add a test that expects `nix repl default.nix` to fail? One question I might have: should there still be a warning or clarification if the --file flag is not used or was deprecation warning from previous version enough?

If anyone has suggestions or edits, let me know.

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

2024-03-27 13:00 UTC, Ericson2314 approved these changes

2024-03-29 10:47 UTC, thufschmitt requested changes
Thanks!

Just a small rewording suggestion for the release notes, but good to go otherwise!

2024-03-29 10:47 UTC, thufschmitt commented on doc/manual/rl-next/remove-repl-flake.md
> +- Fix/Add any tests.
```suggestion
The `repl-flake` experimental feature has been removed. The `nix repl` command now works like the rest of the new CLI in that `nix repl {path}` now tries to load a flake at `{path}` (or fails if the `flakes` experimental feature isn't enabled).*
```

2024-03-29 13:17 UTC, thufschmitt approved these changes

2024-03-29 14:06 UTC, merged