Slight refactors in preparation for #10480
NixOS/nix pull request #10494
Opened 2024-04-13 16:14 UTC by Ericson2314

# Motivation

Code operating on store objects (including creating them) should, in general, use `ContentAddressMethod` rather than `FileIngestionMethod`.

# Context

See also dfc876531f269950a4e183a4f77a813c421d7d64 which included some similar refactors.

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

2024-04-13 16:16 UTC, Ericson2314 commented on src/libexpr/primops.cc
> -            method = FileIngestionMethod { state.forceBool(*attr.value, attr.pos, "while evaluating the `recursive` attribute passed to builtins.path") };
Casting a bool is bad for relying on internal representation details too much, so I made it more explicit.

2024-04-14 13:15 UTC, roberth requested changes
I can't easily infer why this is an improvement, based on the documentation of the `ContentAddressMethod` and `FileIngestionMethod` types.

Specifically, it'd be good to describe how they relate, and perhaps add some guidance on which to pick, if we even need both.

2024-04-14 17:00 UTC, Ericson2314 commented
Hehe very fair. https://github.com/NixOS/nix/pull/10479 and a follow up for store object content addressing are supposed to *finally, thoroughly* answer that question. OK leaving this open until they are done!

2024-05-15 22:21 UTC, Ericson2314 commented
https://github.com/NixOS/nix/pull/10722 is the (barely started draft) of the follow-up I mentioned.

2024-05-17 23:48 UTC, Ericson2314 commented
OK I hope that https://github.com/NixOS/nix/pull/10722 is far enough along that we can make a decision on this :)

2024-05-20 14:03 UTC, roberth approved these changes

2024-05-20 14:03 UTC, merged