Add `SSHMaster::Connection::trySetBufferSize`
NixOS/nix pull request #10765
Opened 2024-05-23 15:57 UTC by Ericson2314

# Motivation

It is unused in Nix currently, but will be used in Hydra. This reflects what Hydra does in https://github.com/NixOS/hydra/pull/1387.

# Context

We may probably to use it more widely for better SSH store performance, but this needs to be subject to more testing before we do that.

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

2024-05-23 16:02 UTC, Ericson2314 commented
Oh wat, segfault in CI in ambient Nix (i.e. nothing to do with this PR)
```
/Users/runner/work/_temp/8e2e66c1-0beb-427b-912b-9e63f8be4be1.sh: line 1:  4963 Segmentation fault: 11  nix --experimental-features 'nix-command flakes' flake check -L
```

2024-05-23 16:24 UTC, vcunat requested changes

2024-05-23 16:24 UTC, vcunat commented on src/libstore/ssh.cc
> +    fcntl(out.get(), F_SETPIPE_SZ, &pipesize);
This looks like wrong fcntl usage to me, by looking at `man fcntl.2`.

2024-05-24 06:35 UTC, roberth commented
> segfault in CI in ambient Nix (i.e. nothing to do with this PR)
> 
> ```
> /Users/runner/work/_temp/8e2e66c1-0beb-427b-912b-9e63f8be4be1.sh: line 1:  4963 Segmentation fault: 11  nix --experimental-features 'nix-command flakes' flake check -L
> ```

Is that on Darwin? Can you get a stack trace for it?

2024-05-24 06:44 UTC, vcunat commented
We didn't post here, but the fcntl calls are wrong.  Setter takes an `int`, not a pointer.  And `getter` takes nothing, returns value.

2024-05-26 17:36 UTC, vcunat commented
Nit: why design the interface with `size_t` when we're only able to implement `int`?

2024-05-27 04:46 UTC, Ericson2314 commented
@vcunat ah it could be `unsigned int`, I just didn't want to accept negative numbers.

2024-05-27 06:22 UTC, roberth commented
Could you add a test? We can't just rely on types here, unfortunately.
You could detect the buffer size by filling a pipe in non blocking mode, without reading it.

2024-05-27 08:00 UTC, vcunat commented
Accepting negative numbers?  Well, if you do an `unsigned int` or `size_t` and pass a too large value, you can end up passing a negative number to the syscall.  So if you don't have code somehow guarding that, I'd say it's better to make the real type visible in the API already.

But perhaps more generally: the function returns the resulting buffer size (or negative error code), so perhaps it would make sense to check the return value?  Overriding buffer size surely won't be a very important error, but perhaps some debug-level logs in case the value differs from what was passed as desired size?  (that could even cover these negative cases by itself)

2025-02-17 00:47 UTC, Ericson2314 commented
Yes, IMO as, one needs to `assert` either way to check it is within `[0, INT_MAX]` neither `int` nor `size_t` is better than the other. I went with `size_t` because I think it is more evocative and portable --- someday, this should be implemented on platforms other than Linux.

2025-02-17 16:52 UTC, roberth approved these changes

2025-02-17 16:55 UTC, Ericson2314 commented on src/libstore/ssh.cc
> +}
I think I'll do this in the future --- e.g. if we're just going to `ssh-ng://` anyways this is temporary.

2025-02-17 16:55 UTC, merged

2025-02-24 13:30 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/2025-02-17-meeting-minutes-213-214/60813/1