Move plugins infra to `libnixmain`
NixOS/nix pull request #11014
Opened 2024-07-02 19:20 UTC by Ericson2314

# Motivation

They are not actually part of the store layer, but instead part of the Nix executable infra (libraries don't need plugins, executables do).

# Context

This is part of a larger project of moving all of our legacy settings infra to libmain, and having the underlying libraries just have plain configuration structs detached from any settings infra / UI layer.

Progress on https://github.com/NixOS/nix/issues/5638

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

2024-07-03 11:14 UTC, roberth requested changes
> libraries don't need plugins, executables do

Executables using libraries also do, and libraries are only useful when executing them, which happens through executables, so this is a red herring.

Suppose I have a plugin that registers a builtin or a new hash function, and I configure that in `nix.conf`, then I would expect *all of Nix* to load it; not just the Nix CLI, but also other executables. Whether they call `nix eval` or `-lnixexprc` should not matter.

Coming to think of it, we could move plugins down into libutil so you can register your own hash functions, although the list of possible hashes is a store thing anyway, but also putting domain logic in libutil is wrong, so moving that is probably better. Plugins in libstore seems ok for now.

2024-07-03 14:39 UTC, Ericson2314 commented
@roberth I did move them to a library `libmain` --- anyone that wants the old behavior can just link that library, and we can make C bindings for it too.

I want to move all the config stuff to `libmain`, actually. Anyone that wants that stuff can just use that library. But I really *don't* want this opinionated logic (plugin stuff or config stuff) in libexpr and libstore (or their dependencies) because it has no place being in a re-usable "backend" library when its a user-interface layer layer, and due to global variables + static initializers its not opt-in.

2024-07-03 16:40 UTC, roberth commented
Ok, I didn't see `libmain` as a viable library for outside consumption, but I see now that it does _not_ depend on `libexpr` (like `libcmd`). Also not too big, fwiw.

It'd be nice to have some sort of description of each library.

https://github.com/NixOS/nix/blob/509be0e77aacd8afcf419526620994cbbbe3708a/src/libmain/nix-main.pc.in#L6

https://github.com/NixOS/nix/blob/509be0e77aacd8afcf419526620994cbbbe3708a/src/libutil/nix-util.pc.in#L6

https://github.com/NixOS/nix/blob/509be0e77aacd8afcf419526620994cbbbe3708a/src/libexpr/nix-expr.pc.in#L6

:thinking:

2024-07-03 18:26 UTC, roberth requested changes
Moving it to a different library is already not so great for a "stable" interface, so let's at least not *re*move it.

Otherwise LGTM.

2024-07-03 18:26 UTC, roberth commented on src/libstore-c/nix_api_store.cc
> -
We can't just remove it. Could you create a new `c` library for this?

2024-07-15 21:45 UTC, Ericson2314 commented
OK, the C function is restored

2024-07-17 07:41 UTC, roberth approved these changes

2024-07-17 07:42 UTC, merged

2024-07-17 17:28 UTC, Ericson2314 commented
Thanks!