feat: Refactor unix domain socket store config
NixOS/nix pull request #11109
Opened 2024-07-15 18:12 UTC by fzakaria

# Motivation

Following what is outlined in #10766 refactor the uds-remote-store such that the member variables (state) don't live in the store itself but in the config object.

Additionally, the config object includes a new necessary constructor that takes a scheme & authority.

Minor:
* code formatting
* cleanup of getting default path
* added some comments

# Context
Please see  #10766
This adds part of the work for the unix domain socket store.

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

2024-07-15 20:34 UTC, Ericson2314 commented on src/libstore/uds-remote-store.cc
> +    return std::format("{}://{}", scheme, getPathOrDefault());
We don't have this on macOS yet, I'm afraid. better just use `+`?

2024-07-15 20:37 UTC, Ericson2314 commented on src/libstore/uds-remote-store.cc
> +    return std::format("{}://{}", scheme, getPathOrDefault());
I am not sure whether we want to stop returning `"daemon"` when the path is not the default, either.

2024-07-15 20:40 UTC, Ericson2314 commented on src/libstore/store-api.cc
> +                return std::make_shared<UDSRemoteStore>(UDSRemoteStoreConfig::scheme, "", params);
```suggestion
                return std::make_shared<UDSRemoteStore>(params);
```
oh sorry, you can keep the old constructor around, precisely for this use case. You can make the old constructor wrap the new one, i.e. `UDSRemoteStore(UDSRemoteStoreConfig::scheme, "", params)` *delegating constructor* call. And then `UDSRemoteStoreConfig::scheme` can go back to being private.

2024-07-15 20:42 UTC, Ericson2314 requested changes
It would be good to have a unit test like https://github.com/NixOS/nix/pull/11108, very close otherwise! :)

2024-07-15 21:30 UTC, Ericson2314 commented on src/libstore/uds-remote-store.hh
> +        assert(scheme == UNIX_SCHEME && "Scheme must be 'unix'");
I think you didn't do this one yet?

2024-07-15 21:37 UTC, Ericson2314 commented on src/libstore/uds-remote-store.hh
> +    static constexpr char const * scheme = "unix";
Can be `protected` now

2024-07-16 02:21 UTC, fzakaria commented
Failing MacOS builds but not sure why -- appreciate any pointer.

2024-07-16 02:53 UTC, Ericson2314 commented on src/libstore/uds-remote-store.hh
> +    public:
```suggestion
protected:
    static constexpr char const * scheme = "unix";
    
public:
```
it's a bit weird looking, but that's how this is generally formatted (pre and post the formatter).

2024-07-16 03:12 UTC, Ericson2314 approved these changes

2024-07-18 03:32 UTC, merged