doc: Add comment for fetchurl for name & url
NixOS/nix pull request #11102
Opened 2024-07-15 02:09 UTC by fzakaria

# Motivation
fetchurl can be given a name and url aside from just the url. Giving a name can be useful if the url has invalid characters such as tilde for the store.

# Context
#10532

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

2024-07-15 02:09 UTC, fzakaria commented
What are the steps to preview the doc ?
I can include a screenshot of how it rendered.

2024-07-15 14:34 UTC, edolstra requested changes

2024-07-15 14:34 UTC, edolstra commented on src/libexpr/primops/fetchTree.cc
> +      - `name` (default: `url without the protocol`)
```suggestion
      - `name` (default: the last path component of the URL)
```
or something like that.

2024-07-15 14:34 UTC, edolstra commented on src/libexpr/primops/fetchTree.cc
> +      (all except url are optional):
```suggestion
      Download the specified URL and return the path of the downloaded file.
      `arg` can be either a string denoting the URL, or an attribute set with the following attributes:
```

2024-07-15 14:34 UTC, edolstra commented on src/libexpr/primops/fetchTree.cc
> +    .args = {"args"},
```suggestion
    .args = {"arg"},
```

2024-07-22 13:49 UTC, edolstra approved these changes

2024-07-22 13:49 UTC, merged