Disable the armv6l and freebsd cross-builds
NixOS/nix pull request #11537
Opened 2024-09-18 19:45 UTC by edolstra

# Motivation
These have been broken for a while (in fact the armv6l build has never succeeded in Hydra), so let's disable them until somebody fixes them.

See https://hydra.nixos.org/eval/1808904#tabs-still-fail.

# Context

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

2024-09-18 21:10 UTC, roberth requested changes
Making good progress:
- #11538
- #11539

Consider merging those instead.

2024-09-19 05:11 UTC, Mic92 commented
Freebsd build fix: https://github.com/NixOS/nix/pull/11542

2024-09-19 07:39 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/2024-09-18-nix-team-meeting-minutes-179/52361/1

2024-09-19 10:22 UTC, closed without merging

2024-09-19 12:16 UTC, Mic92 commented
There is still a FreeBSD compilation issue left. I ask around: https://github.com/NixOS/nix/issues/11546