tests/functional/flakes/run: fix tests in macOS devshell
NixOS/nix pull request #11602
Opened 2024-09-27 09:09 UTC by Mic92

same fix as in 04a47e93f611f08df9f0cadad761a8f5268fff1f

# Motivation

# Context

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

2024-09-27 10:35 UTC, edolstra approved these changes

2024-09-27 10:36 UTC, edolstra commented
I suppose it would be nice to deduplicate this code, maybe it could be moved to `tests/functional/common`?

2024-09-27 10:40 UTC, Mic92 commented
I just don't know what a good name would be, `assertEnvEqual`?

2024-09-30 02:17 UTC, tomberek approved these changes

2024-09-30 10:30 UTC, roberth requested changes
Why is anything setting TMPDIR? This could be a regression

2024-09-30 11:02 UTC, roberth approved these changes
Never mind, already reported. To be fixed. Let's unblock the dev workflow first.

- https://github.com/NixOS/nix/issues/7731

2024-09-30 11:02 UTC, roberth commented on tests/functional/flakes/run.sh
> +# - we unset TMPDIR on macOS if it contains /var/folders
```suggestion
# - we unset TMPDIR on macOS if it contains /var/folders. bad. https://github.com/NixOS/nix/issues/7731
```

2024-09-30 11:37 UTC, merged