doc: note that `nix eval` is eager
NixOS/nix pull request #11670
Opened 2024-10-10 17:03 UTC by fricklerhandwerk

# Motivation
Got bitten by it.

# Context
Boyscout rule.

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

2024-10-12 10:02 UTC, roberth requested changes
Important info, thanks!

2024-10-12 10:02 UTC, roberth commented on src/nix/eval.md
> +This command eagerly evaluates the given Nix expression and prints the result on standard output.
Evaluation is never eager or strict. It always happens the same way.
The difference is in how evaluation is used; not intrinsic to evaluation itself.

```suggestion
This command also evaluates any nested attribute values and list items, and prints the result on standard output.
```

2024-10-13 09:15 UTC, fricklerhandwerk commented on src/nix/eval.md
> +This command also evaluates any nested attribute values and list items, and prints the result on standard output.
```suggestion
This command evaluates the given Nix expression, and prints the result on standard output.

It also evaluates any nested attribute values and list items.
```

2024-10-13 09:38 UTC, roberth approved these changes
I'd say it's a bit more connected, but this is good enough.

2024-10-13 10:31 UTC, merged