fix(libmain/common-args): don't overflow verbosity
NixOS/nix pull request #11853
Opened 2024-11-11 20:49 UTC by xokdvium

# Motivation

This patch gets rid of UB when verbosity overflows to invalid values (e.g. 8). This is actually triggered in unit tests. There are too many occurrences to list, but here's one from the UBSAN log:

`../src/libstore/gc.cc:610:5: runtime error: load of value 8, which is not a valid value for type 'Verbosity'`

Verbosity is now a strong type instead of a plain enum (which is mostly indistinguishable from the underlying type). The type still for all intents and purposes looks like an enumeration, can be used in switches, provides static constexpr member types, but also has member functions.

This makes it very unlikely that we'll have such problems in the future, since now `Verbosity` has a saturating contract for increment/decrement.

Regarding the implementation. This might look like witchcraft, but is completely legal. I've tested that this code (the `Verbosity` static const member pattern) compiles when going back to GCC 7.1.0, Clang 5.0.0 and MSVC 19.21.

# Context

https://github.com/NixOS/nix/issues/10969

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

2024-11-12 09:45 UTC, edolstra requested changes
This is extremely verbose, so I'd really prefer to stick with an enum. Is there any real-world scenario where it being an enum causes a problem?

If we want to keep UBSAN happy, we could use a type specifier for the enum (`enum Verbosity : uint32_t` for instance).

2024-11-12 11:05 UTC, xokdvium commented
> This is extremely verbose, so I'd really prefer to stick with an enum. Is there any real-world scenario where it being an enum causes a problem?
> 
> 
> 
> If we want to keep UBSAN happy, we could use a type specifier for the enum (`enum Verbosity : uint32_t` for instance).

I'm not sure I'm following you about keeping UBSAN happy. Having an enum with an incorrect value is UB and is absolutely an error. Making the underlying type a uint32_t wouldn't change anything. The problem is in the `verbosity + 1`, which does not clamp the value in range.

I debated just fixing the bug and clamp the value in the `-v` handler, but I wanted to make this more foolproof. Using an enum is okay, with since it's a plain C enum it's implicitly convertible from an int and it's very easy to assign an incorrect value to it. Using an `enum class` would get rid of unsafe conversions, but would introduce usability issues.

I do agree that this is a bit verbose, but has the benefit of guarding against unsafe implicit conversions from integral types and giving safe member functions and constructors. Now it's impossible to  accidentally construct/assign an invalid `Verbosity`.

As an alternative we could change it to be an `enum class` with safe freestanding functions. I'm not sure it would be better in terms of readability. If that's also too big of a burden then I'll just revert the change and fix the underlying bug.

IMHO this approach is best for conciseness and barely affects user code, but that's just my personal opinion.

2024-11-12 18:47 UTC, edolstra commented
> Having an enum with an incorrect value is UB and is absolutely an error. 

No. This is simply not a real-world issue. What's the problem here? That a user might specify `-v` 4 billion times and overflow the enum?

2024-11-12 18:57 UTC, xokdvium commented
Sorry, I might have phrased my thoughts incorrectly. By `overflow` I meant no the integer overflow but the fact that the enum value is illegal. E.g. by specifying the `-v` option 8 times the underlying value becomes too large to be represented by enum and does not saturate to the maximum allowed value. 

Here the verbosity does not get clamped to the maximum allowed value `lvlVomit` but instead exceeds `7` and is cast to `Verbosity` (which is UB, since it does not correspond to any enumeration value).

This actually gets asserted in some places:

https://github.com/NixOS/nix/blob/14edb78d5389022ece3c3e9df3689da2f68c479f/src/libutil/error.cc#L266-L267

Here's the minified fix to clarify what the purpose is:

```patch
diff --git a/src/libmain/common-args.cc b/src/libmain/common-args.cc
index 768b2177c..9306acac4 100644
--- a/src/libmain/common-args.cc
+++ b/src/libmain/common-args.cc
@@ -17,7 +17,7 @@ MixCommonArgs::MixCommonArgs(const std::string & programName)
         .shortName = 'v',
         .description = "Increase the logging verbosity level.",
         .category = loggingCategory,
-        .handler = {[]() { verbosity = (Verbosity) (verbosity + 1); }},
+        .handler = {[]() { verbosity = (Verbosity) std::max<std::underlying_type_t<Verbosity>>(verbosity + 1, lvlVomit); }},
     });
 
     addFlag({
```

Sorry for the poor phrasing.

2024-11-13 21:08 UTC, Mic92 commented
> Here the verbosity does not get clamped to the maximum allowed value `lvlVomit` but instead exceeds `7` and is cast to `Verbosity` (which is UB, since it does not correspond to any enumeration value).
> 
> This actually gets asserted in some places:
> 
> https://github.com/NixOS/nix/blob/14edb78d5389022ece3c3e9df3689da2f68c479f/src/libutil/error.cc#L266-L267
> 
> Here's the minified fix to clarify what the purpose is:
> 
> ```diff
> diff --git a/src/libmain/common-args.cc b/src/libmain/common-args.cc
> index 768b2177c..9306acac4 100644
> --- a/src/libmain/common-args.cc
> +++ b/src/libmain/common-args.cc
> @@ -17,7 +17,7 @@ MixCommonArgs::MixCommonArgs(const std::string & programName)
>          .shortName = 'v',
>          .description = "Increase the logging verbosity level.",
>          .category = loggingCategory,
> -        .handler = {[]() { verbosity = (Verbosity) (verbosity + 1); }},
> +        .handler = {[]() { verbosity = (Verbosity) std::min<std::underlying_type_t<Verbosity>>(verbosity + 1, lvlVomit); }},
>      });
>  
>      addFlag({
> ```
> 
> Sorry for the poor phrasing.


The minimal fix sound good to me. @edolstra any concerns about?

2024-11-13 21:12 UTC, Mic92 commented
In the nix meeting @edolstra said, he would be fine with the one-line fix as well.

2024-11-13 23:12 UTC, xokdvium commented
@Mic92, pushed the minimal fix. Sorry once again for poor wording and for going a bit over the top with the initial patch.

2024-11-13 23:26 UTC, Mic92 commented
@mergify queue

2024-11-13 23:52 UTC, merged