Skip tests on systems with restricted usernamespaces
NixOS/nix pull request #12051
Opened 2024-12-14 12:18 UTC by Mic92

Depends on https://github.com/NixOS/nix/pull/12050

2024-12-15 13:58 UTC, roberth approved these changes

2024-12-15 13:58 UTC, roberth commented on tests/functional/common/functions.sh
> +    skipTest "Unprivileged user namespaces are disabled. Run 'sudo sysctl -w /proc/sys/kernel/apparmor_restrict_unprivileged_userns=0' to disable."
```suggestion
    skipTest "Unprivileged user namespaces are disabled. Run 'sudo sysctl -w /proc/sys/kernel/apparmor_restrict_unprivileged_userns=0' to allow, and run these tests."
```

2024-12-16 13:41 UTC, edolstra requested changes

2024-12-16 13:41 UTC, edolstra commented on tests/functional/common/functions.sh
> +  if [[ -f /proc/sys/kernel/apparmor_restrict_unprivileged_userns ]] && [[ $(< /proc/sys/kernel/apparmor_restrict_unprivileged_userns) -eq 1 ]]; then
This test should also be added to `userNamespacesSupported()` in `src/libutil/linux/namespaces.cc`. In fact, if we check for it in Nix itself, then maybe the tests will succeed even if unprivileged user namespaces are restricted.

2024-12-16 14:19 UTC, merged

2024-12-16 15:50 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/2024-12-16-nix-team-meeting-minutes-203/57483/1

2025-01-10 07:08 UTC, bryango commented
@Mic92 can this be backporting to 2.24 & 2.25 as well? I am hitting the same issue as in https://github.com/NixOS/nixpkgs/pull/364176#issuecomment-2543877106

> This is very weird but any idea why the manual-nixos-v2 test now fails to build nix `/nix/store/2yqp6qnxjkm2jxxywh20m30pp8kvksz7-nix-2.24.11.drv` [here](https://github.com/NixOS/nixpkgs/actions/runs/12338986076/job/34434628288), [here](https://github.com/NixOS/nixpkgs/actions/runs/12338716043/job/34434035603), [here](https://github.com/NixOS/nixpkgs/actions/runs/12338629873/job/34434117953), [here](https://github.com/NixOS/nixpkgs/actions/runs/12338195695/job/34432853335) with `build-remote-input-addressed` test failing? (I cannot reproduce the failure locally yet)
> 
> Edit: This is now [built](https://hydra.nixos.org/build/282169832) by Hydra and [restarting](https://github.com/NixOS/nixpkgs/actions/runs/12338629873/job/34443837897) the CI works for me now since the build is cached so 🤷

... and I think backporting this PR may resolve the issue. Thank you!

2025-01-10 13:57 UTC, Mic92 commented
@bryango could you help with the backports?

2025-01-10 14:08 UTC, bryango commented
> could you help with the backports?

I can try, let me see!