darwin installer: remove the file before installing new one
NixOS/nix pull request #3532
Opened 2020-04-24 15:08 UTC by domenkozar

Otherwise results into:

cp: /Library/LaunchDaemons/org.nixos.nix-daemon.plist and /nix/var/nix/profiles/default/Library/LaunchDaemons/org.nixos.nix-daemon.plist are identical (not copied).

2020-04-24 15:28 UTC, domenkozar commented
Not sure this fixes it: `/Library/LaunchDaemons/org.nixos.nix-daemon.plist: service already loaded`

2020-04-24 15:29 UTC, domenkozar commented
Although I'd argue that should be a separate check at installation

2020-04-24 16:52 UTC, LnL7 commented
If we want to support this it's probably best to also ensure that whatever has been loaded by launchd is also removed first.

```
sudo launchctl remove org.nixos.nix-daemon
```

2020-04-30 09:29 UTC, domenkozar commented
I think the script should be idempotent, @grahamc came quite far in https://github.com/NixOS/nix/issues/1551

2020-11-22 20:11 UTC, blast-hardcheese requested changes
seems `0644` is needed

2020-11-22 20:11 UTC, blast-hardcheese commented on scripts/install-darwin-multi-user.sh
> +          install -m 0664 "/nix/var/nix/profiles/default$PLIST_DEST" "$PLIST_DEST"
Compare:
```
brick:~ blast$ launchctl stop org.nixos.nix-daemon && launchctl unload /Library/LaunchDaemons/org.nixos.nix-daemon.plist
brick:~ blast$ sudo install -m 0664 /nix/var/nix/profiles/default/Library/LaunchDaemons/org.nixos.nix-daemon.plist /Library/LaunchDaemons/org.nixos.nix-daemon.plist
brick:~ blast$ launchctl load /Library/LaunchDaemons/org.nixos.nix-daemon.plist && launchctl start org.nixos.nix-daemon
/Library/LaunchDaemons/org.nixos.nix-daemon.plist: Path had bad ownership/permissions
```
with
```
brick:~ blast$ launchctl stop org.nixos.nix-daemon && launchctl unload /Library/LaunchDaemons/org.nixos.nix-daemon.plist
brick:~ blast$ sudo install -m 0644 /nix/var/nix/profiles/default/Library/LaunchDaemons/org.nixos.nix-daemon.plist /Library/LaunchDaemons/org.nixos.nix-daemon.plist
brick:~ blast$ launchctl load /Library/LaunchDaemons/org.nixos.nix-daemon.plist && launchctl start org.nixos.nix-daemon
```

2022-02-21 12:02 UTC, fricklerhandwerk commented
Still relevant.

2023-05-19 12:40 UTC, Ericson2314 commented
I rebased this and changed the mode as @blast-hardcheese accepted. I also made it symbolic because that is much more readable/maintainable.

2023-05-19 13:06 UTC, fricklerhandwerk approved these changes

2023-06-14 17:12 UTC, merged

2024-02-12 18:57 UTC, abathur commented
I'm unsure why it would take so long to manifest as user reports, but it doesn't look like the mode part of this change works, and I'm starting to suspect it's causing some people to turn up with `Bootstrap failed: 5: Input/output error` errors during service init on reinstalls.

```console
$ touch inst1
$ /usr/bin/install -m -rw-r--r-- inst1 inst2
$ ls -la inst*
-rw-r--r-- 1 abathur _lpoperator      0 Feb 12 12:19 inst1
---------- 1 abathur _lpoperator      0 Feb 12 12:21 inst2
```

FWIW I see the same behavior with the nix-installed coreutils implementation of `install`.

User reports I've spotted so far:
- later on in #9702
- #9969
- #9978

Won't be able to start on anything myself until this evening, but I imagine this will cause enough ongoing grief until all of the wild installs with these perms age out that it's worth getting a point release together, and maybe an issue with a lucid explanation and a clear workaround to pin. 

If someone happens to pull together a PR with [installer tests](https://nixos.org/manual/nix/unstable/contributing/testing#installer-tests) configured, I have a spare x86_64-darwin system that I can use to confirm it.

2025-09-13 02:46 UTC, MelvinQc542 commented
I have the same issue.  I was trying to install it clean for a second experimantation runthrough and...  /nix is used.  Followed the same steps everyone describes herein three times, now...  Still same result.  :(

Then I found this [https://iohk.zendesk.com/hc/en-us/articles/4415830650265-Uninstall-nix-on-MacOS](url)

I'll try and I'll be back!

2025-09-13 02:52 UTC, MelvinQc542 commented
> I have the same issue. I was trying to install it clean for a second experimantation runthrough and... /nix is used. Followed the same steps everyone describes herein three times, now... Still same result. :(
> 
> Then I found this [https://iohk.zendesk.com/hc/en-us/articles/4415830650265-Uninstall-nix-on-MacOS](url)
> 
> I'll try and I'll be back!

Turns out it is a 3 year old post...

Looked promising but...  not.

2025-09-13 03:39 UTC, MelvinQc542 commented
This worked!
[https://nix.dev/manual/nix/2.30/installation/uninstall.html](url)