Factor out a `LogStore` interface
NixOS/nix pull request #6220
Opened 2022-03-08 18:50 UTC by Ericson2314

Continue progress on https://github.com/NixOS/nix/issues/5729.

Just as I hoped, this uncovered an issue: the daemon protocol is missing
a way to query build logs. This doesn't effect `unix://`, but does
effect `ssh://`. A FIXME is left for this, so we come back to it later.

2022-03-09 03:00 UTC, Ericson2314 commented
Error is mere timeout.

2022-03-09 14:47 UTC, thufschmitt requested changes
I kinda like the overall idea. A few comments/suggestions

2022-03-09 14:47 UTC, thufschmitt commented on src/libstore/gc-store.cc
> +GcStore & GcStore::require(Store & store)
(I’d even love something that can take a list of classes and return a subclass of all of them. But I’m not sure we can do that 😒)

2022-03-09 14:47 UTC, thufschmitt commented on src/libstore/gc-store.cc
> +GcStore & GcStore::require(Store & store)
Or alternatively make this a store method `Store::as`, so that you can do `store.as<GcStore>().getBuildLog()`

2022-03-09 14:47 UTC, thufschmitt commented on src/libstore/ssh-store.cc
> +    { unsupported("addBuildLog"); }
Mh, I think you’re also missing the override of `addBuildLog`

2022-03-09 15:04 UTC, Ericson2314 commented on src/libstore/ssh-store.cc
> +    { unsupported("addBuildLog"); }
`addBuildLog` is implemented in `remote-store.cc`. One was done but not the other!

2022-03-09 15:29 UTC, Ericson2314 commented on src/libstore/gc-store.cc
> +GcStore & GcStore::require(Store & store)
Done! Didn't make a method because I didn't think classes should be responsible for their own downcasting, but did the rest.,

2022-03-10 08:57 UTC, thufschmitt commented on src/libstore/ssh-store.cc
> +    { unsupported("addBuildLog"); }
Ahah indeed

2022-03-10 08:59 UTC, thufschmitt approved these changes

2022-03-11 10:56 UTC, edolstra commented on src/libstore/build/local-derivation-goal.cc
> +    virtual std::optional<std::string> getBuildLog(const StorePath & path)
Shouldn't this be marked as `override`?

2022-03-11 13:14 UTC, Ericson2314 commented on src/libstore/build/local-derivation-goal.cc
> +    virtual std::optional<std::string> getBuildLog(const StorePath & path)
Good catch!

2022-03-14 09:51 UTC, merged

2022-03-14 15:05 UTC, Ericson2314 commented
Thanks!