don't assume that rev is a SHA1 hash
NixOS/nix pull request #6376
Opened 2022-04-06 17:31 UTC by Uthar

This was a problem when writing a fetcher that uses e.g. sha256 hashes
for revisions. This doesn't actually do anything new, but allows for
creating such fetchers in the future (perhaps when support for Git's
SHA256 object format gains more popularity).

2022-04-07 07:57 UTC, thufschmitt requested changes
Thanks for the PR :)

I’m a bit worried of just disambiguating on the hash length as that seems quite fragile (in particular just encoding the hash differently − base16 vs base32 vs base64 − would break).

I think it would me more reliable to just keep it as-it-is and expect the fetchers to explicitly prefix the hashes if they aren’t a sha1

2022-04-07 18:01 UTC, Uthar commented
Yes, thank you for catching that - let's not get rid of one assumption (SHA1) and introduce another (base16) :-).

I thought maybe something like this: https://github.com/NixOS/nix/commit/2c2fd4946f96e6839ecbfb4cf61318d8910e7e8f Allow plugins to pass their hash type with a prefix, but work unchanged for existing fetchers/flakes which pass a "naked" SHA1.

One idea is that eventually fetchers would be required to pass a "fully qualified" hash (with a prefix), and then try/catch could be removed. Or, maybe it's easy enough to make the required changes while we're at this already? If you think this is a good idea (Maybe it's better to just not touch it?)

2022-04-07 18:01 UTC, Uthar commented
Yes, thank you for catching that - let's not get rid of one assumption (SHA1) and introduce another (base16) :-).

I thought maybe something like this: https://github.com/NixOS/nix/commit/2c2fd4946f96e6839ecbfb4cf61318d8910e7e8f Allow plugins to pass their hash type with a prefix, but work unchanged for existing fetchers/flakes which pass a "naked" SHA1.

One idea is that eventually fetchers would be required to pass a "fully qualified" hash (with a prefix), and then try/catch could be removed. Or, maybe it's easy enough to make the required changes while we're at this already? If you think this is a good idea (Maybe it's better to just not touch it?)

2022-04-07 19:19 UTC, thufschmitt commented
> I thought maybe something like this: https://github.com/NixOS/nix/commit/2c2fd4946f96e6839ecbfb4cf61318d8910e7e8f Allow plugins to pass their hash type with a prefix, but work unchanged for existing fetchers/flakes which pass a "naked" SHA1.

I think you don’t even need that: `parseAny` already takes care of using the prefix if it is specified (the `HashType` that you pass as argument will only be used if the hash isn’t prefixed)

2022-04-07 19:47 UTC, Uthar commented
>  think you don’t even need that: parseAny already takes care of using the prefix if it is specified (the HashType that you pass as argument will only be used if the hash isn’t prefixed)

I tried this (calling just `Hash::parseAny(*s, htSHA1)`, where hash was `sha256:...`), but was getting different results - errors such as:
```
$ src/nix/nix --extra-plugin-files ~/projects/nix-fsl-fetcher/result/bin/libnix-fsl-fetcher.so --extra-experimental-features 'nix-command flakes' flake metadata fsl+https://fossil.galkowski.xyz/nix-fsl-fetcher
error: hash 'sha256:2ea84169c90d58c8f2fd4b810fe9ea70eff17e61d6b403000792c7e0466eb982' should have type 'sha1'
```

This is coming from line 198 in `hash.cc`, where the `htSHA1` is in conflict with the `sha256:` prefix:

https://github.com/NixOS/nix/blob/8b1e328d5d0ae7d3a4a8f6012ec065b59674ed4a/src/libutil/hash.cc#L193-L198

This is why I had to use the try-catch around `parseAnyPrefixed`: this way, we can first handle the case where the hash is "fully qualified" (such as from `plugin-files`, or from future fetchers in Nix core), and if it is not, fall back to the original SHA1 behavior for compatibility with existing fetchers, which pass the naked hash.

2022-04-08 15:32 UTC, thufschmitt approved these changes
> This is coming from line 198 in hash.cc, where the htSHA1 is in conflict with the sha256: prefix:

Oh yes you’re right, I read that too quickly! (maybe worth making the doc clearer on that front too, but that’s a thing for another time)

It’s all good then, thanks :)

2022-04-08 15:56 UTC, merged

2022-04-08 16:28 UTC, Uthar commented
> It’s all good then, thanks :)

Thank you :-)

2022-04-08 16:47 UTC, edolstra commented
I think for Git and Mercurial, we should verify that the rev is 20 bytes (or at least 20 bytes, if we want to be future-proof). Otherwise you can now pass an MD5 hash and Git will interpret it as a shortened rev, which is not what we want.

2022-04-08 17:50 UTC, Uthar commented
> I think for Git and Mercurial, we should verify that the rev is 20 bytes

Could this be done like this? https://github.com/NixOS/nix/pull/6387

Prevents e.g. `nix flake metadata git+https://github.com/nixos/nix?rev=md5:646af7325d93f98802b989f8a8e008a2`