libfetchers/git: hardcode `--git-dir`
NixOS/nix pull request #6440
Opened 2022-04-23 21:23 UTC by Ma27

To demonstrate the problem:

* You need a `git` at 2.33.3 in your $PATH
* An expression like this in a git repository:

  ``` nix
  {
    outputs = { self, nixpkgs }: {
      packages.foo.x86_64-linux = with nixpkgs.legacyPackages.x86_64-linux;
        runCommand "snens" { } ''
          echo ${(builtins.fetchGit ./.).lastModifiedDate} > $out
        '';
    };
  }
  ```

Now, when instantiating the package via `builtins.getFlake`, it fails on
Nix 2.7 like this:

    $ nix-instantiate -E '(builtins.getFlake "'"$(pwd)"'").packages.foo.x86_64-linux'
    fatal: unsafe repository ('/nix/store/a7j3125km4h8l0p71q6ssfkxamfh5d61-source' is owned by someone else)
    To add an exception for this directory, call:

    	git config --global --add safe.directory /nix/store/a7j3125km4h8l0p71q6ssfkxamfh5d61-source
    error: program 'git' failed with exit code 128
    (use '--show-trace' to show detailed location information)

This breaks e.g. `nixops`-deployments using flakes with similar
expressions as shown above.

The cause for this is that `git(1)` tries to find the highest
`.git`-directory in the directory tree and if it finds a such a
directory, but with another owning user (root vs. the user who evaluates
the expression), it fails as above. This was changed recently to fix
CVE-2022-24765[1].

By explicitly specifying `--git-dir`, Git assumes to be in the top-level
directory and doesn't attempt to look for a `.git`-directory in the
parent directories and thus the code-path leading to said error is never
reached.

[1] https://lore.kernel.org/git/xmqqv8veb5i6.fsf@gitster.g/

cc @edolstra @thufschmitt @Ericson2314

2022-04-24 11:07 UTC, Ma27 commented
Note: this doesn't seem to fix `sudo nixos-rebuild switch --flake .#`. Workaround for that is `sudo nixos-rebuild switch --flake path:.#`. Any ideas on how to fix that?

2022-04-24 11:41 UTC, bjornfor commented
Related? https://github.com/NixOS/nix/issues/6443

2022-04-24 11:49 UTC, Ma27 commented
yes :)

2022-04-24 16:09 UTC, Ma27 commented
With the latest commit, `nixos-rebuild` works for me as well.

2022-04-25 11:28 UTC, thufschmitt requested changes
Looks good, thanks :)

Since we’re adding more complexity to these `git` calls, do you think you could factor that out? Having one `runGit(Path path, std::vector<std::string> args)` command that would morally run `runProgram("git", true, { "-C", path, "--git-dir", getGitDir(), ..args}` (or something along those lines). Not sure whether the git calls are similar enough to warrant it, but it’s annoying to have all these calls with some very similar arguments everywhere.

Also, it might be a bit silly right now since the Git used in the flake doesn’t have the patch, but I’d love to see a regression test for this. Not sure how we could do it without having to resort to a costly vm test though since it involves medling with the permissions

2022-04-25 12:23 UTC, Ma27 commented
> Also, it might be a bit silly right now since the Git used in the flake doesn’t have the patch, but I’d love to see a regression test for this. Not sure how we could do it without having to resort to a costly vm test though since it involves medling with the permissions

We could do that by updating the nixpkgs pin in this repo I guess.

2022-04-26 12:08 UTC, Ma27 commented
> Since we’re adding more complexity to these git calls, do you think you could factor that out? Having one runGit(Path path, std::vector<std::string> args) command that would morally run runProgram("git", true, { "-C", path, "--git-dir", getGitDir(), ..args} (or something along those lines). Not sure whether the git calls are similar enough to warrant it, but it’s annoying to have all these calls with some very similar arguments everywhere.

The problem is, all of those calls are slightly different: e.g. different `RunOptions`, potentially a different `gitDir` (because of `repoDir = cacheDir` etc.). We could either factor out the creation of `{ "-C", repoDir, ... }` into a function (but that doesn't seem to be a benefit) or we could move the entire `runProgram`-call out, but then we'd have to take care of edge-case option for `runProgram` which also doesn't seem to be that beneficial.

@thufschmitt  In other words, I'd prefer to see this merged considering that it is an issue on unstable and 21.11 and would unblock a few people I guess.

2022-04-26 12:50 UTC, thufschmitt approved these changes
> @thufschmitt In other words, I'd prefer to see this merged considering that it is an issue on unstable and 21.11 and would unblock a few people I guess.

Fair point. I feared that trying to factor this out would make everything a bit awkward. Let’s merge this as-it-is then, I’ll just open an issue about the test

2022-04-26 12:50 UTC, merged

2022-04-27 14:40 UTC, thufschmitt commented
> @thufschmitt could you please add backport labels to 2.7 and 2.8

Both failed :unamused: 

I’ve manually created a backport PR for 2.8 (not sure why the bot failed). Do you think you can create one for 2.7 (there’s a small merge conflict) ?

2022-05-03 18:11 UTC, alexshpilkin commented on src/libfetchers/git.cc
>      return chomp(runProgram("git", true, { "-C", path, "--git-dir", ".git", "rev-parse", "--abbrev-ref", "HEAD" }));
Should this have used getGitDir() as well?

2022-05-03 18:16 UTC, alexshpilkin commented on src/libfetchers/git.cc
>      return chomp(runProgram("git", true, { "-C", path, "--git-dir", ".git", "rev-parse", "--abbrev-ref", "HEAD" }));
Is there a reason why this shouldn’t have been changed as well?

```suggestion
    return chomp(runProgram("git", true, { "-C", path, "--git-dir", getGitDir(), "rev-parse", "--abbrev-ref", "HEAD" }));
```

2022-05-09 09:37 UTC, edolstra commented
@Ma27 I don't understand this part:
```
     auto gitDir = getEnv("GIT_DIR");
```
How does it make sense to have a global environment variable that overrides the `.git` directory *for all repositories*?

2022-05-09 09:41 UTC, Ma27 commented
@edolstra that's a variable from Git itself. If it's declared, `.git` is named differently, so `--git-dir=.git` doesn't work.

2022-05-09 09:50 UTC, edolstra commented
I know that, but why does it make sense for Nix to use that variable? Git deals with only one repo, whereas Nix's Git fetcher deals with potentially multiple local repos, all of which may have a different `GIT_DIR` setting. If we really want to support this use case, then it should probably be a `git` input attribute. (And to be honest, overriding `.git` seems like one of those "just don't do that" things that only complicate the code...)

2022-05-09 12:34 UTC, thufschmitt commented
I confess didn’t think about it too much and I assumed that it was here for the `git+file` case (where we might indeed need to honor it since it’s a property of the workspace).

But indeed, even in that case it shouldn’t be blindly picked from the environment − and in any other case we probably shouldn’t respect it since the git repos are fully handled by Nix (so unless I’m missing something, there’s no good reason to use something else than the default `.git`)

2022-05-12 13:46 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/tweag-nix-dev-update-30/19112/1

2022-05-24 11:52 UTC, Ma27 commented
> But indeed, even in that case it shouldn’t be blindly picked from the environment

Yeah thinking a bit more about this and I guess it may cause more problems than it solves, so we should replace `auto gitDir = getGitDir();` with `auto gitDir = ".git";` (the variable is still important because of `gitDir = ".";` for cached repos).

2022-05-24 12:21 UTC, Ma27 commented
Followup in https://github.com/NixOS/nix/pull/6567 @edolstra :)