Make flake metadata evaluation behaviour more discoverable
NixOS/nix pull request #6592
Opened 2022-05-30 16:27 UTC by ckiee

See commit messages. Builds and works for me in a `nix develop` shell.

2022-05-30 16:28 UTC, ckiee commented
cc #4945

2022-06-04 14:21 UTC, tomberek commented
These commits seem to imply the entire flake.nix cannot perform evaluation. Closer would be to say that a flake.nix contains up to three attributes at the top-level: `inputs`, `nixConfig`, and `outputs`. Where inputs and nixConfig must be simple key-value attrsets with no function evaluation. Outputs must be a function definition for which the function body can perform any pure Nix evaluation (modulo the usage of `--impure`,`--restrict-eval`, etc).

2022-06-08 11:43 UTC, thufschmitt requested changes
Thanks, that's a great addition :)

I'm a bit annoyed by the pointer to a github issue, though. If there's some valuable information in the issue that's missing from the manual, then it should be ported to the manual rather than linked from the source code

2022-06-08 13:13 UTC, ckiee commented
> I'm a bit annoyed by the pointer to a github issue, though. If there's some valuable information in the issue that's missing from the manual, then it should be ported to the manual rather than linked from the source code

That would be nice and it did annoy me a bit too but I'm not sure how to do that. `flake.md` is a manual page, not a reference guide or something else. It seems weird to include a `## Flake metadata evaluation` or whatnot in what seems like more of a casual introduction. (*"As an example, [...]"*)

If you have any ideas on how to make that fit in that'd be nice.

2022-06-08 13:26 UTC, edolstra commented on src/nix/flake.md
> +The following attributes are supported in `flake.nix`, but all attributes other than `outputs`
This does not read very well ("The following attributes..." followed by two sentences that are *not* the list of attributes).  Better to phrase it like "Flake attribute must be written using a limited subset bla bla... The following attributes are supported:".

2022-06-08 14:31 UTC, ckiee commented
> We definitely shouldn't link to GitHub issues in error messages, except maybe if there is an actual bug, **which is not the case here.**

[Are you sure?](https://github.com/NixOS/nix/issues/6631)

2026-05-18 17:18 UTC, tomberek commented
stale: re-open and re-base as needed

2026-05-18 17:18 UTC, closed without merging