Improve shell completion of flake inputs
NixOS/nix pull request #6693
Opened 2022-06-20 02:47 UTC by ncfavier

Makes `nix build ~/flake1 ~/flake2 --update/override-input <Tab>` do the right thing:

1. do tilde expansion
2. defer the completion until all arguments are parsed, otherwise `_installables` is empty and nix assumes we mean the current directory
3. complete inputs of all given flakes instead of just the first one

For 2, I also considered making arguments like `installables` "incremental", i.e. add the arguments to `_installables` as they arrive, but this turned out to be a mess to implement. Also with the chosen approach we can complete things like `nix build --update-input foo<Tab> flake`, although this is unreliable (e.g. it won't work with an empty prefix because bash apparently does not insert an empty word there).

2022-07-08 10:23 UTC, ncfavier commented
@thufschmitt sorry to ping but it would be nice to have this in the 2.10 milestone as it's just quality of life improvements without changes to any exposed interfaces.

2022-07-11 09:05 UTC, ncfavier commented
> @thufschmitt sorry to ping but it would be nice to have this in the 2.10 milestone as it's just quality of life improvements without changes to any exposed interfaces.

or @edolstra

2022-07-11 13:02 UTC, thufschmitt requested changes
Thanks (and thanks for the ping, I kinda missed the PR the first time).
A couple of small comments on the code, but looks good overall.

My main issue is that this doesn't come with any test. But since there wasn't any before either I don't think that should be a blocker.

2022-07-11 13:04 UTC, ncfavier commented on src/libcmd/command.hh
> +    virtual std::vector<std::string> getFlakesForCompletion()
The reason is to do tilde expansion in a single place, rather than ask each implementation of `getFlakesForCompletion` to do it.

2022-07-11 13:12 UTC, ncfavier commented on src/libutil/args.hh
> +    virtual void doCompletions() { }
Renamed and added a comment.

I'll try to add tests.

2022-07-11 13:19 UTC, thufschmitt commented
> My main issue is that this doesn't come with any test. But since there wasn't any before either I don't think that should be a blocker.

Working on that in another branch

2022-07-12 07:11 UTC, thufschmitt approved these changes
Thanks, looks good :)

(For future reference: There's a follow-up PR adding tests at https://github.com/NixOS/nix/pull/6784)

2022-07-12 07:11 UTC, thufschmitt commented on src/libcmd/command.hh
> +    virtual std::vector<std::string> getFlakesForCompletion()
I see… I'm not entirely convinced that's the best long-term solution, but that'll definitively do it for the time being

2022-07-12 07:12 UTC, merged

2023-03-29 23:31 UTC, Ericson2314 commented on src/libcmd/command.hh
> +    virtual std::vector<std::string> getFlakesForCompletion()
We only complete one argument, right? So I think doing it in `getFlakesForCompletion` is fine?

I changed this in #8131

2023-03-29 23:31 UTC, Ericson2314 commented on src/libcmd/command.hh
> +    virtual std::vector<std::string> getFlakesForCompletion()
We only complete one argument, right? So I think doing it in `getFlakesForCompletion` is fine?

I changed this in #8131