flakes: apply templates partially on conflicts
NixOS/nix pull request #6699
Opened 2022-06-21 16:37 UTC by tennox

Addressing #6542, followup on https://github.com/NixOS/nix/commit/452ffe5464f20ac44a01c536349895d138150a96 by @thufschmitt 

Will still **exit with non-zero exit code** and **clearly prompt which files to merge**:
 ```
$ nixx flake init -t github:numtide/devshell
wrote: /home/manu/dev/stuff/gopassbridge/.envrc
refusing to overwrite existing file '/home/manu/dev/stuff/gopassbridge/.gitignore'
-> merge manually with '/nix/store/ksmwhyghjwb4d9dw6hcpbvng1msdvjim-source/template/.gitignore'
wrote: /home/manu/dev/stuff/gopassbridge/devshell.toml
wrote: /home/manu/dev/stuff/gopassbridge/flake.nix
error: Encountered 1 conflicts - please merge manually
 ```
(`nixx` is my alias for the self-built nix binary)

2022-06-22 18:27 UTC, thufschmitt requested changes
Thanks.

A few suggestions on the implementation and the messages, but look good overall

2022-06-22 18:27 UTC, thufschmitt commented on src/nix/flake.cc
> +        auto success = false;
Actually you probably don't need it at all since `success == false` <=> `!conflictedFiles.empty()`

2022-06-22 18:27 UTC, thufschmitt commented on src/nix/flake.cc
> +                            printError("refusing to overwrite existing file '%s' - please merge manually with '%s'", to2, from2);
```suggestion
                            printError("refusing to overwrite existing file '%s'\n please merge it manually with '%s'", to2, from2);
```

2022-06-26 17:17 UTC, tennox commented on src/nix/flake.cc
> +            throw Error("Encountered %d conflicts - please merge manually", conflictedFiles.size());
I went for `"Encountered %d conflicts - see above"` as I can imagine a scenario where you see only some of the conflicts when there's a longer command output, and it's good to get an intuition of how many conflicts to look for.

2022-06-29 11:41 UTC, thufschmitt commented on src/nix/flake.cc
> +            throw Error("Encountered %d conflicts - please merge manually", conflictedFiles.size());
I wanted to avoid the singular/plural issue that always come when you show an explicit number. But it's not a big deal anyways

2022-06-29 14:30 UTC, thufschmitt approved these changes
Thanks :)

I've taken the liberty of pushing some quick tests, I'll merge as soon as the CI is green

2022-06-29 16:21 UTC, merged