libfetchers: avoid api.github.com ratelimit if no github token is set
NixOS/nix pull request #7039
Opened 2022-09-14 12:18 UTC by Mic92

If we don't have any github token, we won't be able to fetch private repos, but we are also more likely to run into API limits since we don't have a token. To mitigate this only ever use the github api if we actually have a token.

2022-09-22 09:00 UTC, Mic92 commented
Anything else that needs to be done here?

2022-09-22 09:28 UTC, pleshevskiy commented on src/libfetchers/github.cc
> +        const auto urlFmt =
```suggestion
        const auto urlFmt =
            host != "github.com"
            ? "https://%s/api/v3/repos/%s/%s/tarball/%s"
            : headers.empty()
            ? "https://%s/%s/%s/archive/%s.tar.gz"
            : "https://api.%s/repos/%s/%s/tarball/%s"
```

2022-09-22 20:44 UTC, knedlsepp commented on src/libfetchers/github.cc
> +        // If we have no auth headers than we default to the public archive
than -> then

2022-09-22 20:44 UTC, knedlsepp commented on src/libfetchers/github.cc
>          // FIXME: use regular /archive URLs instead? api.github.com
The FIXME can be dropped now.

2022-10-01 18:49 UTC, SuperSandro2000 commented
Can this please be merged for the next nix release? Since more and more people switched to flakes we are almost always hitting that rate limit.

2022-10-18 21:28 UTC, SuperSandro2000 commented
bump

2022-10-26 08:19 UTC, Mic92 commented
> This seems important to get in, is there anything blocking it?

The lack of Nix maintainers to merge.

2022-10-27 08:05 UTC, thufschmitt requested changes
Looks good at a glance, but you'll have to update `tests/github-flakes.nix` as it as a mock of the github API and will need to be extended to support this change.

You can run it with `nix build .\#hydraJobs.tests.githubFlakes`

2022-10-29 19:54 UTC, SuperSandro2000 commented
https://github.com/Mic92/nix-1/pull/1

2022-10-30 06:13 UTC, Mic92 commented
The tests have been extended to cover both cases (download via public archive and download via api)

2022-10-31 10:48 UTC, thufschmitt approved these changes
Thanks, looks good :)

And thanks for improving the readability of the github test too :)

(Ideally it'd be nice to serve `github.com` and `api.github.com` separately in it, but that's out of scope here)

2022-10-31 10:48 UTC, merged

2022-12-18 15:13 UTC, Kha commented
> To mitigate this only ever use the github api if we actually have a token.

This doesn't seem to be true, the `getRevFromRef` function just above `getDownloadUrl` still uses the API. I just ran into a rate limit error from that. Not sure there's a better way to avoid that than `git ls-remote`.

2022-12-18 19:41 UTC, Mic92 commented
At least this lets you download archives, which is more often used in CIs than updating flakes.