Fix why-depends for CA derivations
NixOS/nix pull request #7337
Opened 2022-11-23 16:45 UTC by Radvendii

why-depends assumed that we knew the output path of the second argument. For CA derivations, we might not know until it's built. One way to solve this would be to build the second installable to get the output path.

In this case we don't need to, though. If the first installable (A) depends on the second (B), then getting the store path of A will necessitate having the store path B. The contrapositive is, if the store path of B is not known (i.e. it's a CA derivation which hasn't been built), then A does not depend on B.

2022-11-23 16:56 UTC, thufschmitt requested changes
A minor request, but :+1: otherwise. Thanks :)

Can you just add a test? I think it's enough to do like in https://github.com/NixOS/nix/blob/master/tests/ca/build-dry.sh, just re-source the `why-depends.sh` test but with `NIX_TESTS_CA_BY_DEFAULT=1`

2022-11-23 16:56 UTC, thufschmitt commented on src/nix/why-depends.cc
> +        auto derivedDependency = dependency->toDerivedPath();
Maybe add a comment explaining why we don't want to build it?

2022-11-23 17:09 UTC, Radvendii commented
Is it worth wrapping this:
```
std::visit(overloaded {
            [](const DerivedPath::Opaque & nodrv) -> std::optional<StorePath> {
                return { nodrv.path };
            },
            [&](const DerivedPath::Built & hasdrv) -> std::optional<StorePath> {
                if (hasdrv.outputs.size() != 1) {
                    throw Error("argument '%s' should evaluate to one store path", dependency->what());
                }
                auto outputMap = store->queryPartialDerivationOutputMap(hasdrv.drvPath);
                auto maybePath = outputMap.find(*hasdrv.outputs.begin());
                if (maybePath == outputMap.end()) {
                    throw Error("unexpected end of iterator");
                }
                return maybePath->second;
            },
        }, derivedDependency.raw())
 ```
 
 into a function? This seems like a common thing to want "give me the store path if you already have it, otherwise nullopt"

2022-11-23 17:41 UTC, thufschmitt approved these changes

2022-11-23 19:16 UTC, merged

2023-02-03 09:54 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/tweag-nix-dev-update-43/25185/1