Post build hook signing
NixOS/nix pull request #7408
Opened 2022-12-06 04:22 UTC by endgame

At least until #6960 is fixed, switch the recommended approach to one which signs all derivations that end up in binary caches.

2022-12-06 15:28 UTC, thufschmitt approved these changes
Makes sense semantically speaking. And I actually like this style better. Deferring to @fricklerhandwerk for merging.

2022-12-07 10:11 UTC, fricklerhandwerk requested changes
Thanks @endgame! Left suggestions for wording. Also please note the [general contribution guidelines](https://github.com/NixOS/nix.dev/blob/master/CONTRIBUTING.md?plain=1#L175-L176), which you probably have not seen because they are not linked in the Nix contribution guide. (We will catch up eventually, but you're warmly invited to make a PR to the manual!)

@NixOS/documentation-team This whole directory are tutorials which don't really belong here. We should maintain them anyway, and move them to nix.dev eventually.

2022-12-07 10:11 UTC, fricklerhandwerk commented on doc/manual/src/advanced-topics/post-build-hook.md
>  `trusted-public-keys` and `substituters` options:
Please generously add links to definitions. They don't help much if you know what you're doing or what the terms mean, but require manual search for everyone else, slowing down adoption and increasing frustration if the search goes astray.

Reworded the sentence to match the order of terms in the example.

"Access" sounds more unsurprising than "consume" and "write to", and should capture both meanings good enough.

```suggestion
Then, update [`nix.conf`] on any machine that will access the cache with its URL ([`substituters`]) and public key ([`trusted-public-keys`]):

[`nix.conf`]: ../command-ref/conf-file.md
[`substituters`]: ../command-ref/conf-file.md#conf-substituters
[`trusted-public-keys`]:  ../command-ref/conf-file.md#conf-trusted-public-keys
```

2022-12-07 10:11 UTC, fricklerhandwerk commented on doc/manual/src/advanced-topics/post-build-hook.md
> +
These are instructions which correctly started as imperative. No reason to switch to descriptive phrasing.

```suggestion
On machines which build packages for the cache, update [`nix.conf`] with the path to their key file ([`secret-key-files`]):

[`secret-key-files`]: ../command-ref/conf-file.md#secret-key-files

    secret-key-files = /etc/nix/key.private

```

2022-12-07 10:47 UTC, endgame commented
Rewritten to capture the spirit of suggestions, plus some guesses at the anchors in the conf-file (how do I check those?).

2022-12-07 11:27 UTC, fricklerhandwerk commented on doc/manual/src/advanced-topics/post-build-hook.md
> +Then update [`nix.conf`](../command-ref/conf-file.md) on any machine that will access the cache, adding the cache URL to [`substituters`](../command-ref/conf-file.md#conf-substituters) and the public
```suggestion
Then update [`nix.conf`](../command-ref/conf-file.md) on any machine that will access the cache.
Add the cache URL to [`substituters`](../command-ref/conf-file.md#conf-substituters) and the public key to [`trusted-public-keys`](../command-ref/conf-file.md#conf-trusted-public-keys):
```

Use short sentences where possible. Please keep the reference links, it makes the source much easier to read and maintain. The links are also easier to maintain in bulk when they are not inlined, i.e. when we rename files. (Search/replace still has to be checked manually until we have automatic link checks.)

See https://github.com/NixOS/nix.dev/blob/master/CONTRIBUTING.md#guides

This is not consistent at all yet, but we're only starting to work on this.

2022-12-07 11:27 UTC, fricklerhandwerk commented
At the worst, the anchors are visible in the manual: https://nixos.org/manual/nix/unstable/command-ref/conf-file.html

There is also a file which generates them, which I'm about to make more readable: https://github.com/NixOS/nix/pull/7379/files

2022-12-07 12:54 UTC, fricklerhandwerk approved these changes

2022-12-07 12:55 UTC, merged

2022-12-08 17:13 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/tweag-nix-dev-update-41/23848/1