InstallableFlake::toDerivedPaths(): Support paths and store paths
NixOS/nix pull request #7484
Opened 2022-12-20 14:10 UTC by edolstra

This makes `nix build` work on paths (which will be copied to the store) and store paths (returned as is). E.g. the following flake output attributes can be built using `nix build .#foo`:

```
foo = ./src;
foo = self.outPath;
foo = builtins.fetchTarball { ... };
foo = (builtins.fetchTree { .. }).outPath;
foo = builtins.fetchTree { .. } + "/README.md";
foo = builtins.storePath /nix/store/...;
```

Note that this is potentially risky, e.g.

```
foo = /.;
```

will cause Nix to try to copy the entire file system to the store.

What doesn't work yet:

```
foo = self;
foo = builtins.fetchTree { .. };
```

because we don't handle attrsets with an outPath attribute in it yet, and

```
foo = builtins.storePath /nix/store/.../README.md;
```

since result symlinks have to point to a store path currently (rather than a file inside a store path).

Extracted from the lazy-trees branch. Fixes #7417. This PR also refactors `Installables` to merge `InstallableFlake::toDerivations()` into `toDerivedPaths()`, which simplifies the interface.

2023-01-03 10:23 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/2022-12-23-nix-team-meeting-minutes-19/24400/1

2023-01-03 17:19 UTC, Ericson2314 commented
https://github.com/NixOS/nix/pull/7543 This should help us handle the remaining cases.

2023-01-03 21:16 UTC, Ericson2314 approved these changes
I think this PR is an excellent first step, and we should merge it as is, but we should take away the "fixes #7543" because there is more to that issue remaining.

I am happy to do the rest myself.

2023-01-04 07:00 UTC, thufschmitt requested changes
That's a great addition!

2023-01-04 08:10 UTC, tomberek commented
Looking to include the more advanced features to support:
- attrsets with outPath
- derivations without drvPath
- derivation without drvPath with multiple outputs with strings
- - derivation without drvPath with multiple outputs with paths
- 
https://github.com/NixOS/nix/compare/master...flox:nix:fix-7417 (WIP)

2023-01-10 13:56 UTC, edolstra commented on src/nix/profile.cc
>                  element.source = ProfileElementSource {
They largely contain the same info now, but that might not be the case in the future.

2023-01-10 14:21 UTC, edolstra commented on src/nix/profile.cc
> +           multiple derivations. So pick one arbitrarily. */
I've added a FIXME me for this.

2023-01-10 14:22 UTC, edolstra commented on src/nix/build.cc
> +
IMHO in C++ there isn't much risk here (unlike e.g. in a dynamically scoped language like Python).

2023-01-10 14:57 UTC, merged

2023-01-10 16:39 UTC, tomberek commented
> * attrsets with outPath
> * derivations without drvPath
> * derivation without drvPath with multiple outputs with strings
> * derivation without drvPath with multiple outputs with paths

@edolstra would you want the above implemented in a new PR?

2023-01-10 20:12 UTC, Ericson2314 commented on tests/flakes/build-paths.sh
> +    a6 = flake2.outPath;
How does this work? This should have an `!out!drvPath` string context.