tests: Fix flake- and sandbox-based build on Darwin
NixOS/nix pull request #7588
Opened 2023-01-12 00:53 UTC by centromere

The following changes permit nix to be built properly in a sandboxed environment via `nix build .#`.

2023-01-12 11:31 UTC, edolstra commented
Can you explain this a bit more? What didn't work? We build Nix in a sandboxed environment all the time...

2023-01-12 20:47 UTC, centromere commented
Hi @edolstra, sure:

```
➜  nix-official git:(master) git rev-parse HEAD
eaa20f25747eb025c7c4e69fa83f0e455a65393f
➜  nix-official git:(master) nix -L build --rebuild .#
nix> unpacking sources
nix> unpacking source archive /nix/store/8jcyi0vm2fxi6sf62yhc4kkmxj84canp-source
nix> source root is source
...
nix>   LD     src/nix/nix
nix>   GEN    doc/manual/nix.json
nix>   GEN    doc/manual/conf-file.json
nix> # @docroot@: https://nixos.org/manual/nix/unstable/contributing/hacking.html#docroot-variable
nix>   GEN    doc/manual/src/command-ref/new-cli
nix>   GEN    doc/manual/src/command-ref/conf-file.md
nix>   GEN    doc/manual/nix.conf.5
nix>   LD     src/libexpr/tests/libexpr-tests
nix> # @docroot@: https://nixos.org/manual/nix/unstable/contributing/hacking.html#docroot-variable
nix>   GEN    doc/manual/src/command-ref/new-cli
nix>   GEN    doc/manual/generated/man1/nix3-manpages
nix> buildPhase completed in 4 minutes 58 seconds
nix> running tests
nix> check flags: -j12 SHELL=/nix/store/1bsjl5incfnszv7scdh4d02sh45vw2w1-bash-5.1-p16/bin/bash profiledir=\$\(out\)/etc/profile.d PRECOMPILE_HEADERS=1 VERBOSE=y check
nix>   TEST
nix>   TEST
nix>   TEST
nix> Running main() from /tmp/nix-build-gtest-1.12.1.drv-0/source/googletest/src/gtest_main.cc
nix> [==========] Running 200 tests from 44 test suites.
nix> [----------] Global test environment set-up.
...
nix> [----------] 3 tests from pathExists
nix> [ RUN      ] pathExists.rootExists
nix> [       OK ] pathExists.rootExists (0 ms)
nix> [ RUN      ] pathExists.cwdExists
nix> [       OK ] pathExists.cwdExists (0 ms)
nix> [ RUN      ] pathExists.bogusPathDoesNotExist
nix> unknown file: Failure
nix> C++ exception with description "error: getting status of /home/schnitzel/darmstadt/pommes: Operation not permitted" thrown in the test body.
nix> [  FAILED  ] pathExists.bogusPathDoesNotExist (0 ms)
nix> [----------] 3 tests from pathExists (0 ms total)
...
nix> [----------] Global test environment tear-down
nix> [==========] 200 tests from 44 test suites ran. (13 ms total)
nix> [  PASSED  ] 199 tests.
nix> [  FAILED  ] 1 test, listed below:
nix> [  FAILED  ] pathExists.bogusPathDoesNotExist
nix>  1 FAILED TEST
nix>   YOU HAVE 2 DISABLED TESTS
nix> make: *** [mk/lib.mk:118: libutil-tests_RUN] Error 1
nix> make: *** Waiting for unfinished jobs....
nix> Running main() from /tmp/nix-build-gtest-1.12.1.drv-0/source/googletest/src/gtest_main.cc
nix> [==========] Running 15 tests from 3 test suites.
nix> [----------] Global test environment set-up.
...
nix> [ RUN      ] references.scan
nix> [       OK ] references.scan (0 ms)
nix> [----------] 1 test from references (0 ms total)
nix> [----------] Global test environment tear-down
nix> [==========] 15 tests from 3 test suites ran. (2 ms total)
nix> [  PASSED  ] 15 tests.
nix> libc++abi: terminating with uncaught exception of type nix::SysError: error: getting status of /nix/var/nix/profiles/per-user/root/channels/nixpkgs: Operation not permitted
nix> make: *** [mk/lib.mk:118: libexpr-tests_RUN] Abort trap: 6
error: builder for '/nix/store/j2k35fbymp3zhsgwf633avhhscgh67dq-nix-2.13.0pre20230112_eaa20f2.drv' failed with exit code 2;
       last 10 log lines:
       > [----------] 1 test from references
       > [ RUN      ] references.scan
       > [       OK ] references.scan (0 ms)
       > [----------] 1 test from references (0 ms total)
       >
       > [----------] Global test environment tear-down
       > [==========] 15 tests from 3 test suites ran. (2 ms total)
       > [  PASSED  ] 15 tests.
       > libc++abi: terminating with uncaught exception of type nix::SysError: error: getting status of /nix/var/nix/profiles/per-user/root/channels/nixpkgs: Operation not permitted
       > make: *** [mk/lib.mk:118: libexpr-tests_RUN] Abort trap: 6
       For full logs, run 'nix log /nix/store/j2k35fbymp3zhsgwf633avhhscgh67dq-nix-2.13.0pre20230112_eaa20f2.drv'.
➜  nix-official git:(master)
```

This is on macOS Ventura 13.1 (22C65).

`nix.conf`:
```
experimental-features = nix-command flakes
build-users-group = nixbld
sandbox = true
builders = @/etc/nix/machines
builders-use-substitutes = true
```

2023-03-10 13:47 UTC, Ericson2314 commented
Triaged in the Nix team meeting:

- assigned to @fricklerhandwerk
- @tomberek will try to reproduce
- @ericson3214: Happy to see run unit tests being run with a non-standard store dir, but still wants them to be run with the regular ones too.

2023-03-13 12:08 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/2023-03-10-nix-team-meeting-minutes-39/26279/1

2023-03-13 12:19 UTC, fricklerhandwerk requested changes

2023-03-13 12:19 UTC, fricklerhandwerk commented on flake.nix
> +
Let's not test with non-standard store directory yet, and make this PR only about parameterising the store directory in the code. We can expand on the testing later and instead get the relevant change here merged soon.

2023-03-13 12:38 UTC, tomberek commented
Unable to reproduce the original problem (with or without sandboxing), though the fix to [src/libexpr/tests/value/context.cc](https://github.com/NixOS/nix/pull/7588/files#diff-ba75589dfc86524fce2907465490b4177ca8a55fe24eeb47b1b3d8fa5792c9bd) seems beneficial.

Is there something else about the setup that is needed to trigger the original motivation?

2023-03-13 20:25 UTC, centromere commented
@tomberek:
```
➜  nix-official git:(master) git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
➜  nix-official git:(master) git rev-parse HEAD
a387f46967ae9eb97eaeb17ca26fb583283815ce
➜  nix-official git:(master) nix -L build .#
nix> unpacking sources
nix> unpacking source archive /nix/store/mvndm071344fd141adwy3czy82wwrdk3-source
nix> source root is source
...
nix> [----------] 7 tests from LevenshteinDistance/LevenshteinDistanceTest
nix> [ RUN      ] LevenshteinDistance/LevenshteinDistanceTest.CorrectlyComputed/0
nix> [       OK ] LevenshteinDistance/LevenshteinDistanceTest.CorrectlyComputed/0 (0 ms)
nix> [ RUN      ] LevenshteinDistance/LevenshteinDistanceTest.CorrectlyComputed/1
nix> [       OK ] LevenshteinDistance/LevenshteinDistanceTest.CorrectlyComputed/1 (0 ms)
nix> [ RUN      ] LevenshteinDistance/LevenshteinDistanceTest.CorrectlyComputed/2
nix> [       OK ] LevenshteinDistance/LevenshteinDistanceTest.CorrectlyComputed/2 (0 ms)
nix> [ RUN      ] LevenshteinDistance/LevenshteinDistanceTest.CorrectlyComputed/3
nix> [       OK ] LevenshteinDistance/LevenshteinDistanceTest.CorrectlyComputed/3 (0 ms)
nix> [ RUN      ] LevenshteinDistance/LevenshteinDistanceTest.CorrectlyComputed/4
nix> [       OK ] LevenshteinDistance/LevenshteinDistanceTest.CorrectlyComputed/4 (0 ms)
nix> [ RUN      ] LevenshteinDistance/LevenshteinDistanceTest.CorrectlyComputed/5
nix> [       OK ] LevenshteinDistance/LevenshteinDistanceTest.CorrectlyComputed/5 (0 ms)
nix> [ RUN      ] LevenshteinDistance/LevenshteinDistanceTest.CorrectlyComputed/6
nix> [       OK ] LevenshteinDistance/LevenshteinDistanceTest.CorrectlyComputed/6 (0 ms)
nix> [----------] 7 tests from LevenshteinDistance/LevenshteinDistanceTest (0 ms total)
nix> [----------] Global test environment tear-down
nix> [==========] 293 tests from 55 test suites ran. (61 ms total)
nix> [  PASSED  ] 292 tests.
nix> [  FAILED  ] 1 test, listed below:
nix> [  FAILED  ] pathExists.bogusPathDoesNotExist
nix>  1 FAILED TEST
nix>   YOU HAVE 2 DISABLED TESTS
nix> make: *** [mk/lib.mk:118: libstore-tests-exe_RUN] Error 1
nix> libc++abi: terminating with uncaught exception of type nix::SysError: error: getting status of /nix/var/nix/profiles/per-user/root/channels/nixpkgs: Operation not permitted
nix> make: *** [mk/lib.mk:118: libexpr-tests_RUN] Abort trap: 6
error: builder for '/nix/store/irawmigb7f2rd2xb5m0m4y2k9g54jdk4-nix-2.15.0pre20230313_a387f46.drv' failed with exit code 2;
       last 10 log lines:
       > [  PASSED  ] 292 tests.
       > [  FAILED  ] 1 test, listed below:
       > [  FAILED  ] pathExists.bogusPathDoesNotExist
       >
       >  1 FAILED TEST
       >   YOU HAVE 2 DISABLED TESTS
       >
       > make: *** [mk/lib.mk:118: libstore-tests-exe_RUN] Error 1
       > libc++abi: terminating with uncaught exception of type nix::SysError: error: getting status of /nix/var/nix/profiles/per-user/root/channels/nixpkgs: Operation not permitted
       > make: *** [mk/lib.mk:118: libexpr-tests_RUN] Abort trap: 6
       For full logs, run 'nix log /nix/store/irawmigb7f2rd2xb5m0m4y2k9g54jdk4-nix-2.15.0pre20230313_a387f46.drv'.
```

This is on macOS Ventura 13.2.1 (22D68).

`nix.conf`:
```
experimental-features = nix-command flakes
build-users-group = nixbld
sandbox = true
builders = @/etc/nix/machines
builders-use-substitutes = true
```

2023-10-18 20:30 UTC, n8henrie commented
Trying to tinker on https://github.com/NixOS/nix/issues/4119, I'm also failing on `aarch64-darwin` due to:

```
"error: getting status of /home/schnitzel/darmstadt/pommes: Operation not permitted"
```

2023-12-18 14:37 UTC, tomberek commented
@centromere I've tried again with a few variations in settings and multiple darwin machines. I am still unable to reproduce.

I started to rebase to master and noticed the changes to context.cc tests seem to have been made in the meantime: https://github.com/NixOS/nix/blob/master/tests/unit/libexpr/value/context.cc#L65

2023-12-19 00:01 UTC, centromere commented
@tomberek I created this ticket nearly a year ago. I am unable to reproduce now, so whatever happened between now and then seems to have fixed things. If I run into the issue again I'll create a new ticket/PR.

2023-12-19 00:01 UTC, closed without merging