`nix flake check` skips derivations for foreign systems
NixOS/nix pull request #7759
Opened 2023-02-05 23:54 UTC by peterbecich

# Context

> nix flake check breaks on IFD in multi-platform flake
> https://github.com/NixOS/nix/issues/4265

# Motivation

`nix flake show` now skips derivations for foreign systems: https://github.com/NixOS/nix/pull/6988

This PR borrows from that PR to implement the same behavior for `nix flake check`.

Here is a Flake project which I believe uses IFD: https://github.com/srid/haskell-template

Using Nix 2.12.0 on a `x86_64-linux`, the result of `nix flake check` is:

```
$ nix flake check
warning: Git tree '/home/peterbecich/haskell/libraries/haskell-template' is dirty
error: a 'aarch64-linux' with features {} is required to build 
'/nix/store/jlcg48nsm1dpblvg9wj6zq19c3mswg40-cabal2nix-haskell-template.drv',
 but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test, uid-range}
(use '--show-trace' to show detailed location information)
```

With this PR, `nix flake check` produces:

```
~/nix/nix/outputs/out/bin/nix flake check
warning: Git tree '/home/peterbecich/haskell/libraries/haskell-template' is dirty
warning: The check omitted these incompatible systems (use '--all-systems' to check all):
warning: aarch64-darwin
warning: aarch64-linux
warning: armv5tel-linux
warning: armv6l-linux
warning: armv7l-linux
warning: i686-linux
warning: mipsel-linux
warning: powerpc64le-linux
warning: riscv64-linux
warning: x86_64-darwin
```

With this PR and the `--all-systems` flag, it produces an error like before:
```
 ~/nix/nix/outputs/out/bin/nix flake check --all-systems
warning: Git tree '/home/peterbecich/haskell/libraries/haskell-template' is dirty
error:
       … while checking flake output 'packages'

         at «none»:0: (source not available)

       … while checking the derivation 'packages.aarch64-linux.default'

         at «none»:0: (source not available)

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: a 'aarch64-linux' with features {} is required to build 
'/nix/store/jlcg48nsm1dpblvg9wj6zq19c3mswg40-cabal2nix-haskell-template.drv',
 but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test, uid-range}
```

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or bug fix: updated release notes

2023-02-06 09:51 UTC, yajo commented
If you want better backwards compatibility, you can do this opt-in and instead add the flag `--current-system-only` or `--skip-foreign-systems` or similar.

2023-02-07 04:27 UTC, peterbecich commented
That's a good idea, I don't have an opinion one way or the other.

Can somebody make a decision:
- check all systems by default; `--current-system-only` flag or similar
or
- check only current system by default; `--all-systems` flag
  - consistent with `nix flake show --all-systems`

2023-02-07 07:48 UTC, NobbZ commented
Personally I am in the "change the default behaviour" camp and only check the current system.

This usually makes it easier to run a check on the terminal.

Keeping the current behaviour as the default would usually end up in a workflow like the following:

1. run the check,
2. see it fail because of IFD
3. be confused
4. google
5. try check with `--current-system-only` (or whatever name would be agreed upon)
6. see an error that the flag wasn't known as nix is too old

Optionally replace 6 with "get a suceeding check".

By changing the default, we can get this down to:

1. run the check
2. see it pass/fail

In worst case people had an older nix and they would google and should see, oh, new behaviour introduced in nix 2.30, I'm only on 2.15, so I have to update.

CI that indeed relies on multi-arch checks would need to update their scripts, as they update their nix version. I think this is fine. At least they are relying on *experimental software* which is allowed to break or change its behaviour in subtle ways.

We just need to be clear in the release notes that this is intended behaviour.

Break things now!

Once 3.0 got released we can not as easily!

2023-02-08 07:58 UTC, peterbecich commented
Okay, I will keep the current behavior then, default is current system only.

> PS: I am a big fan of --system … to be able to override the current system to play with aarch64 and i686 builds on my x86_64 box, so that should definitely be respected as "current system"

This is a good idea; can we review this PR now and implement that later in a subsequent PR? It can be done for both `nix flake show` and `nix flake check`. I don't know when the date is for the next release; hoping to merge this PR before.

2023-02-20 14:58 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/2023-02-17-nix-team-meeting-minutes-33/25624/1

2023-03-11 02:49 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/2023-02-17-nix-team-meeting-minutes-33/25624/2

2023-03-26 19:27 UTC, peterbecich commented
@fricklerhandwerk okay, thank you.

IMO `--current-system-only` is better than `--keep-going` with deferred error.

This will help `nix flake check --current-system-only` in GitHub Actions. If there is a deferred error code thrown by `nix flake check --keep-going`, the GitHub Action will fail.

2023-03-26 20:29 UTC, peterbecich commented
Here are tests;

default behavior maintained:
```
$ ./result/bin/nix flake check ~/haskell/libraries/purescript-bridge2                                                                                                1 
...
error: a 'aarch64-linux' with features {} is required to build '/nix/store/d0w4jfn7ldnr7j1xipfzp3rmk7mwwf1j-cabal2nix-example.drv', 
but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test, uid-range}

```

The `--current-system-only` flag:
```
$ ./result/bin/nix flake check --current-system-only ~/haskell/libraries/purescript-bridge2                                                                          warning: unknown flake output 'haskellFlakeProjectModules'
warning: The check omitted these incompatible systems:
warning: aarch64-darwin
warning: aarch64-linux
warning: armv5tel-linux
warning: armv6l-linux
warning: armv7l-linux
warning: i686-linux
warning: mipsel-linux
warning: powerpc64le-linux
warning: riscv64-linux
warning: x86_64-darwin
```

2023-03-26 20:31 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/2023-03-17-nix-team-meeting-minutes-41/26614/3

2023-03-27 12:14 UTC, fricklerhandwerk commented
Discussed in Nix team meeting:

@peterbecich we agreed on changing the default behavior and make `--all-systems` work exactly as in `nix flake show`. Thanks for your patience!

@thufschmitt will shepherd the PR to the finish line.

2023-03-27 13:44 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/2023-03-27-nix-team-meeting-minutes-44/26759/1

2023-04-06 07:35 UTC, peterbecich commented
Great, thank you. This last commit https://github.com/NixOS/nix/commit/d00082f6fd773743369a30c34c60953cfd103060 should be deleted.

2023-04-29 01:36 UTC, peterbecich commented
The PR currently implements the correct behavior: https://github.com/NixOS/nix/pull/7759#issuecomment-1485039086

2023-05-19 08:26 UTC, peterbecich commented
Can this be merged? Thank you

2023-05-22 08:31 UTC, thufschmitt requested changes
Sorry for the delay @peterbecich, this fell down the cracks. Just one small comment on the message that gets printed, but good otherwise.

2023-05-23 04:58 UTC, thufschmitt approved these changes

2023-05-23 04:59 UTC, thufschmitt commented
Awesome, thanks

2023-05-23 04:59 UTC, merged

2023-05-27 22:34 UTC, peterbecich commented
This PR did not fix `nix flake check` for multi-platform Flakes using Hydra jobs: https://github.com/NixOS/nix/issues/4265#issuecomment-1565663797

I don't know about multi-platform Flakes using IFD.