Create `nix add-derivation` command
NixOS/nix pull request #7887
Opened 2023-02-23 05:35 UTC by Ericson2314

# Motivation

Implementing approved #7828

TODO:

 - [ ] Fix `DerivationTest.Derivation_impure_from_json` unit test test
 - [ ] Need to validate derivation so we don't write illegal ones to the store
 - [ ] Write documentation (it is just copied right now)

# Context

#7828

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

2023-02-24 08:19 UTC, roberth commented
I believe this command should be under `store`, like `add-file`. While that wouldn't be consistent with `nix show-derivation`, I believe that this command should also be moved. By doing so, the top level namespace is relatively clean, which helps with discoverability. It also follows the noun-verb naming rule a bit better.

2023-02-24 13:13 UTC, Ericson2314 commented
I opened #7903 for the naming of this command.

2023-03-01 23:32 UTC, Ericson2314 commented
OK the check boxes are checked! This still sucks in many ways

 - Derivation name is specified via CLI flag
 - Input-addressed output paths must be manually computed
 - Documentation sucks --- we should document the derivation format separately from these utility command man pages

But it's an experimental command, so I am tempted to say we should just land a beachhead and then improve it.

2023-03-20 13:55 UTC, Ericson2314 commented on src/nix/add-derivation.md
> +This command reads from the given path a JSON representation of a
```suggestion
This command reads from standard input a JSON representation of a
```

2023-03-27 13:19 UTC, fricklerhandwerk commented
Triaged in the Nix team meeting 2023-03-23:

- @edolstra: Does this import only one derivation at a time?
- @ericson2314: Production quality / High performance language interface would use bindings
    - this is for easy experimentation and making the CLI complete on principle
    - It's a limitation, but OK for the moment
- idea approved, assigned to @roberth

2023-03-30 09:34 UTC, roberth requested changes
We need to resolve the `--name` situation first.
Adding a prototype of this command first would be counterproductive, because we know that it barely serves a purpose. It only serves to annoy the poor soul who tries to use it before it's done. (and the test case I suppose, although like 80% of the test value is already delivered: showing that the code is mostly ok but the design isn't right)

2023-03-30 15:23 UTC, Ericson2314 commented on src/libstore/derivations.cc
> +    const Store & store, std::string_view drvName,
There is now a `name` field!

2023-03-30 16:06 UTC, roberth commented on src/nix/add-derivation.md
> +This command reads from the given path a JSON representation of a
It's back :ghost:

2023-03-30 16:15 UTC, roberth reviewed
Looks alright.
TODO
 - [ ] Apply the suggestion in add-derivation.md

Scoped out, prio mine.

 - should have: Rename the command
 - nice to have: Streaming JSON Lines

2023-03-30 17:09 UTC, Ericson2314 commented on src/nix/add-derivation.md
> +This command reads from the given path a JSON representation of a
And it's gone again! :ghost:

2023-03-30 20:14 UTC, fricklerhandwerk commented
Isn't this a plumbing command? `nix store add-derivation`. @Ericson2314 last time you proposed having only convenience wrappers at the top level.

2023-03-31 12:07 UTC, Ericson2314 commented
@fricklerhandwerk Since we already have `nix show-derivation` I soon as well add this first and then separately go about finding a new home for both of them.

In generally I rather separate the tasks of making sure we have commands for missing functionality, and reorganizing the commands, as the former is somewhat easier and the latter requires more team thinking which can keep open PRs for an indefinite amount of time if it blocks the former.

2023-03-31 12:21 UTC, roberth commented
Doing it this way does add more tech debt in the form of either missing release notes or potentially giving users a command the we're going to break.
Not sure if refinancing the tech debt is progress.
Ideally we can rename it now, but otherwise I lean slightly towards merging? Stagnation causes even more suffering.

2023-04-02 00:37 UTC, fricklerhandwerk commented
Side note: Progress is not a value in itself. No change can also mean stability one can build on. Otherwise I agree on the tech dept, let's keep it minimal.

2023-04-02 15:29 UTC, Ericson2314 commented
If you think it's fine I'll go ahead and do `nix derivation {add,show}` right away.

2023-04-02 18:19 UTC, Ericson2314 commented
I went ahead and did that.

Do note that I think there are still other breaking changes that would happen, relating to the fact that the JSON format for derivations (used by `show-dervation`) doesn't yet follow the API guidelines.

2023-04-07 12:31 UTC, roberth approved these changes

2023-04-07 13:02 UTC, merged

2023-05-05 19:54 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/this-month-in-nix-docs-2-april-2023/27899/1