Fix empty "error:" message when a top-level goal is never built
NixOS/nix pull request #8003
Opened 2023-03-08 11:49 UTC by edolstra

# Motivation

E.g.

```
# nix build --store /tmp/nix --file tests/ca/content-addressed.nix
error: builder for '/nix/store/da7d4sy5lmppl9a173hc8h00xd8vbng6-simple-input-addressed.drv' failed with exit code 1;
       last 1 log lines:
       > error: executing '/nix/store/dsd5gz46hdbdk2rfdimqddhq6m8m8fqs-bash-5.1-p16/bin/bash': No such file or directory
       For full logs, run 'nix log /nix/store/da7d4sy5lmppl9a173hc8h00xd8vbng6-simple-input-addressed.drv'.
error:
```

This is because the file contains multiple goals, one of which fails, and the others are never built because of that, and therefore have status `MiscFailure` and an empty `errorMsg`.

This introduces an "abandoned" status and sets `errorMsg` accordingly.

# Context

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

2023-03-08 14:04 UTC, Ericson2314 approved these changes

2023-03-08 14:07 UTC, Ericson2314 commented
Actually, this should get a test. It is easy to write the failing derivation. What about the others? I forget whether without `--keep-going` the other derivations in progress will be killed or just wait to be run.

2023-03-08 14:07 UTC, Ericson2314 requested changes
Either a test, or some sort of TODO that this is currently too hard to test.

2023-06-14 23:15 UTC, neilmayhew commented
Any chance of getting this moving again?

2026-05-18 17:39 UTC, tomberek commented
stale: re-open and re-base as needed

2026-05-18 17:39 UTC, closed without merging