Update macOS uninstall instructions
NixOS/nix pull request #8210
Opened 2023-04-12 15:34 UTC by theutz

Accounting for `/etc/bash.bashrc`

# Motivation
Update the docs to avoid errors when re-installing nix.

# Context
Here's the error message produced after following the existing instructions, and re-running the installer:

```
I back up shell profile/rc scripts before I add Nix to them.
I need to back up /etc/bash.bashrc to /etc/bash.bashrc.backup-before-nix,
but the latter already exists.

Here's how to clean up the old backup file:

1. Back up (copy) /etc/bash.bashrc and /etc/bash.bashrc.backup-before-nix
   to another location, just in case.

2. Ensure /etc/bash.bashrc.backup-before-nix does not have anything
   Nix-related in it. If it does, something is probably quite
   wrong. Please open an issue or get in touch immediately.

3. Once you confirm /etc/bash.bashrc is backed up and
   /etc/bash.bashrc.backup-before-nix doesn't mention Nix, run:
   mv /etc/bash.bashrc.backup-before-nix /etc/bash.bashrc
```

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] documentation in the internal API docs
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

2023-04-12 16:45 UTC, fricklerhandwerk requested changes

2023-04-12 16:45 UTC, fricklerhandwerk commented on doc/manual/src/installation/installing-binary.md
> +1. Edit `/etc/zshrc`, `/etc/bashrc`, and `/etc/bashrc` to remove the lines sourcing
```suggestion
1. Edit `/etc/zshrc`, `/etc/bashrc`, and `/etc/bash.bashrc` to remove the lines sourcing
```

Did you mean that?

2023-04-12 16:46 UTC, theutz commented on doc/manual/src/installation/installing-binary.md
> +1. Edit `/etc/zshrc`, `/etc/bashrc`, and `/etc/bashrc` to remove the lines sourcing
Doh. Sure did!

2023-04-12 20:10 UTC, fricklerhandwerk approved these changes
Thanks!

2023-04-17 16:32 UTC, closed without merging

2023-04-18 09:13 UTC, fricklerhandwerk commented
@theutz Hm, apparently auto-merge didn't trigger a merge. Can you revive the branch or open a new PR?

2023-04-18 10:20 UTC, theutz commented
For sure! Got it live at #8236.