Display valid installable in InstallableDerivedPath::parse warning
NixOS/nix pull request #8214
Opened 2023-04-13 14:34 UTC by raphaelr

# Motivation
The warning message should produce an installable name that can be passed to `nix build`, `nix path-info`, etc. again. Since the CLI expects that the .drv path and the output names are separated by a caret, the warning message must also separate the .drv path and output names with a caret.

However, `DerivedPath::Built.to_string()` uses an exclamation point as the separator instead.

This changes the warning message from:
> If this command is now failing try again with '/nix/store/foo.drv!*'

to:
> If this command is now failing try again with '/nix/store/foo.drv^*'

# Context

https://github.com/NixOS/nix/pull/7600#issuecomment-1506443774

Instead of printing a `DerivedPath::Built`, print the plain .drv store path followed by the outputs specificiation.

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] documentation in the internal API docs
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

2023-04-13 14:48 UTC, Ericson2314 commented
This is not a good way to fix this, I am afraid, because it is just duplicating the pretty-printing logic; this means more places to double check and no doubt this sort of mistake will crop up again.

Can you instead add a `char separator` parameter to `DerivedPath::to_string`?

2023-04-13 14:48 UTC, Ericson2314 requested changes
See previous comment

2023-04-14 12:08 UTC, Ericson2314 commented
@raphaelr Thank so much!

2023-04-14 12:16 UTC, Ericson2314 commented
I am talking to fellow team member @roberth. it would be good to have some test for this; it would also be good to perhaps make this method private (or `static` in the file) and just expose a `to_string` / `to_string_legacy` (and likewise `parse` / `parse_legacy`, and likewise updating the unit tests `src/libstore/tests/derived-path.cc`).

This is, however, a lot to ask from you a volunteer, who was told "oh this would be a quick fix!" :). So if you like we're happy to do the rest.

2023-04-14 12:30 UTC, raphaelr commented
Sure, feel free to update this PR.

2023-04-15 00:48 UTC, Ericson2314 approved these changes
OK I think this is ready now.

2023-04-15 01:12 UTC, Ericson2314 commented
Note that during development I temporary renamed `to_string` to `to_string_modern`. This let me better audit the ones that were switched from `!` to `^`.

- They all appeared to be diagnostics for humans, except for the one in `Store::queryMissing` which is neither exposed to other processes or humans (and thus should also be safe to change).
- Just the daemon protocol is using the legacy root.
- The legacy SSH protocol uses `StorePathWithOutputs` which is "even more legacy" (also uses `!` FWIW).

2023-04-15 12:14 UTC, roberth approved these changes

2023-04-15 12:15 UTC, merged