Make print-build-logs a setting
NixOS/nix pull request #8323
Opened 2023-05-12 11:43 UTC by edolstra

# Motivation

This allows you to put `print-build-logs = true` in nix.conf.
    
# Context

Issue #5858.

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] documentation in the internal API docs
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

2023-05-12 11:54 UTC, edolstra commented
Adding a `log-format` setting is slightly trickier, since the old and new CLI have different defaults.

2023-05-12 19:58 UTC, cole-h approved these changes
As someone who tried to get something very similar in before (but much more wide-reaching: https://github.com/NixOS/nix/pull/3961), I'd be very very happy to see this merged!

2023-05-13 13:01 UTC, Ericson2314 requested changes
> Adding a `log-format` setting is slightly trickier, since the old and new CLI have different defaults.
Can't we just agument a enum with an extra case "default", which keeps the current per-CLI defaults?

I would rather have that than the `print-build-logs` setting.

2023-05-13 13:02 UTC, Ericson2314 commented
Yeah just make it `std::optional<LogFormat>`

2023-05-19 10:40 UTC, edolstra commented
> Yeah just make it `std::optional<LogFormat>`

It's not that easy, because setting `log-format` in `nix.conf` would change the behaviour of both the old and new CLI, which is probably not what you want. E.g. setting `log-format = bar-with-logs` to enable log output would change the old CLI to use the progress bar.

2023-06-02 15:24 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/2023-06-02-nix-team-meeting-minutes-59/28666/1

2024-02-03 04:39 UTC, Qyriad commented
This PR needs a rebase, but is there anything else blocking it?

2025-12-26 08:08 UTC, Lyndeno commented
This would be useful to be merged. Any way I can help?

2026-05-18 17:46 UTC, tomberek commented
stale: re-open and re-base as needed

2026-05-18 17:46 UTC, closed without merging