hacking guide: use more self-descriptive section headings
NixOS/nix pull request #8556
Opened 2023-06-20 11:45 UTC by fricklerhandwerk

"Nix with flakes" doesn't thell what the section is about.

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

2023-06-20 12:43 UTC, iFreilicht requested changes
Mostly looks good to me. Makes a lot of sense to link the experimental features directly as well.

However, the heading changes break the `#classic-nix` and `#nix-with-flakes` anchors. please fix those. While you're at it, you might as well fix the `#target-platform` anchor as well, maybe by renaming the respective heading to "Target platforms".

2023-06-21 07:49 UTC, fricklerhandwerk commented
@iFreilicht done. "Platforms" originally was "Target platforms", but @roberth changed it for undocumented reasons. Should ask before reverting that. I don't have strong opinions on this.

2023-06-21 10:38 UTC, roberth commented
>  @roberth changed it for undocumented reasons

Virtually undocumented. The commit message, "Corrections and additions for cross" is not a lot to go by, I have to admit.

Nix is not a compiler, so it does not have a target system, where target is defined as usual by the [GNU docs](https://gcc.gnu.org/onlinedocs/gccint/Configure-Terms.html).

The compiler used to compile Nix does have a target, but that's a contrived way of thinking about a program that's incompatible with how for example Nixpkgs works. It does a good job at hiding target, so if in doubt, you probably shouldn't use the term.

Looking at the first sentence

> Nix can be built for various platforms:

"built for" means the _host_ platform.

If we pretend it's about _target_, that sentence would have to be "Nix can be built to compile to various platforms", which is nonsense.

2023-06-21 10:42 UTC, roberth submitted a review, later dismissed
Remove target; see earlier comment.

2023-06-21 10:42 UTC, roberth commented on doc/manual/src/contributing/hacking.md
> +You can also build Nix for one of the [supported target platforms](#platforms).
```suggestion
You can also build Nix for one of the [supported platforms](#platforms).
```

2023-06-21 10:42 UTC, roberth commented on doc/manual/src/contributing/hacking.md
> +You can also build Nix for one of the [supported target platforms](#platforms).
```suggestion
You can also build Nix for one of the [supported platforms](#platforms).
```

2023-06-21 10:43 UTC, roberth commented
We could make cross compilation a lot easier using `default.nix`, as it can take the systems as parameters, fwiw.

2023-06-21 13:12 UTC, iFreilicht approved these changes

2023-06-22 11:45 UTC, merged