libexpr: extend `Value::print` to allow limited depth
NixOS/nix pull request #8566
Opened 2023-06-22 04:38 UTC by inclyc

# Motivation

This is an extension for setting limited depth for `nix::Value` printing. Sometimes this list is fairly large because of recursive set inside nix, and printing in a desired depth make things much easier for users who just want to see limited depth (for example, when using `nix repl`, we may only want to see `depth = 1`  attribute fields, instead of digging into it (basically unreadable). Maybe we can extend `nix repl` after this change, for limited depth printing.

# Context

I'm writting a nix language server which would like to provide consistent developer experience between editors and official nix implementation, and `nix::Value::print` seems a good way to show values (there is no other good public method to do so). And this method may takes long time to finish.

Related PR: https://github.com/nix-community/nixd/pull/149

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] documentation in the internal API docs
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

2023-06-22 08:53 UTC, roberth requested changes
I'd say a depth parameter is a last resource, but a valid solution that's fairly easy to implement and maintain. You might want to consider, although you probably already have:

1. only explore one layer at a time, lazily, on-demand, interactive, etc
2. a mix of "depth first" and "breadth first" until you reach an output size limit; some clever balancing act. Should work reasonably even for `pkgs`.
3. depth limit. The minimum limit is still terrible for something like `pkgs`

Assuming 1 is not feasible for you and 2 is a "research project" and a lot more to test and review, let's go ahead with this.

This needs testing. Ideally I'd like to see a new unit test in src/libexpr/tests (I hate to say that this function is not unit tested yet), but perhaps it would also be nice to have a depth parameter for `nix-instantiate`, which uses this method.

2023-06-22 08:53 UTC, roberth commented on src/libexpr/eval.cc
> +        str << "«depth»";
```suggestion
        str << "«too deep»";
```

Not to suggest that there's a representation of some sort of depth concept at that location.

2023-06-22 09:11 UTC, inclyc commented
Thanks for reviewing my PRs ❤️ .


> a mix of "depth first" and "breadth first" until you reach an output size limit; some clever balancing act. Should work reasonably even for `pkgs`.


Before addressing review comments, would you like to accept patches that trying to stop printing to `ostream` if it reaches some size limit also? Because `pkgs` is fairly big even when `depth = 1`.

> I'd say a depth parameter is a last resource, but a valid solution that's fairly easy to implement and maintain. 

Yes, it gives us reasonable outputs because nix language itself is structural and nested, so given a "depth" argument somehow preserve enough information instead of digging in some irrelavent attribute paths.

> This needs testing. Ideally I'd like to see a new unit test in src/libexpr/tests (I hate to say that this function is not unit tested yet), but perhaps it would also be nice to have a depth parameter for nix-instantiate, which uses this method.

Thanks, I would like to see how to add these tests then.

2023-07-01 18:05 UTC, roberth approved these changes

2023-07-01 18:08 UTC, merged