add nix-store --query --valid-derivers command
NixOS/nix pull request #8863
Opened 2023-08-23 16:05 UTC by symphorien

# Motivation
On typical nixos installations, nixos-rebuild creates .drv files for all store paths of the system, but the deriver field of the db comes from hydra. If a dependency of a fixed output derivation changed between the time hydra built something and nixos-rebuild was called, the local .drv and the deriver provided by hydra will not match. In this case,
nix-store --query --deriver /store/path returns a missing .drv file, whereas we have at least one other deriver of this store path locally.

This commit adds a new command `nix-store --query --valid-derivers` which prints .drv files which can build the specified output *and actually exist locally*.
The intended final use case of this contribution is to be able to link an executable in the store to the store path of its source via the src field of its deriver. (specifically: nixseparatedebuginfod uses that to provide source code to gdb)

# Context
This is an alternative to #8538 suggested in https://github.com/NixOS/nix/pull/8538#issuecomment-1676146508

This just exposes `Store::queryValidDerivers(const StorePath & path)` in the cli.

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] documentation in the internal API docs
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

2023-08-24 08:02 UTC, iFreilicht requested changes
Looks pretty good! Documentation was updated in the right places and is generally useful, scope is good, and the tests mostly look good, too. Some small qualitative notes and questions, no major concerns from my side.

2023-08-24 08:03 UTC, iFreilicht commented
Ah, one thing I forgot: You might want to add a note to `rl-next.md` so this feature shows up in the release notes :)

2023-08-24 08:37 UTC, symphorien commented on tests/dependencies.sh
> +if [[ -n "${NIX_DAEMON_PACKAGE:-}" ]] && ! isDaemonNewer "2.18pre0"; then
Indeed I did not change the daemon, my bad, I copy pasted this from https://github.com/NixOS/nix/pull/8538

2023-08-24 08:40 UTC, symphorien commented on src/nix-store/nix-store.cc
> +            auto sorted = store->topoSortPaths(result);
it's copy pasted from how --references &co work, tbh :)

2023-08-24 09:20 UTC, iFreilicht reviewed
Tiny suggestion for the release notes, otherwise this looks perfect now!

2023-08-24 09:20 UTC, iFreilicht commented on src/nix-store/nix-store.cc
> +            auto sorted = store->topoSortPaths(result);
Ah ok. I think it's fine then, being consistent with the behavior of other query commands makes sense.

2023-08-25 15:05 UTC, Ericson2314 reviewed
I would like this to do CA derivations (when enabled) too

But maybe because that is an experimental feature we can do later?

2023-08-25 16:50 UTC, iFreilicht commented
That seems to me like it should be a feature of the `queryValidDerivers` function in general, right? Doesn't it handle CA drvs already?

2023-08-26 15:39 UTC, roberth commented
> That seems to me like it should be a feature of the `queryValidDerivers` function in general

I agree. It's about fixing a bug behind the correct interface this already uses. (and I believe that was also John's understanding of it - more of an fyi comment?)

2023-08-26 15:45 UTC, roberth approved these changes
This is great!

2023-08-26 15:47 UTC, roberth commented
If you could rebase to resolve the conflict, this will be ready for merging.
Also consider https://github.com/NixOS/nix/pull/8863/files#r1305784673

2023-09-01 12:16 UTC, merged

2023-09-01 13:20 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/2023-09-01-nix-team-meeting-minutes-84/32466/1