fix some nix commands not creating the user's default profile if missing
NixOS/nix pull request #8984
Opened 2023-09-15 13:14 UTC by e-nikolov

# Motivation

In nix versions prior to 2.14.0, the default profile location was at `/nix/var/nix/profiles/per-user/$USER` and the following commands used to create it if it does not exist yet:
- `nix run ...`
- `nix shell ...`
- `nix develop ...`
- `nix flake init ...`
- `nix flake new ...`

After the default profile location changed to `$HOME/.local/state/nix/profiles` those commands no longer create the profile. This causes issues on new nix installations when executing a `nix run ... ` command that expects the profile to exist, e.g. installing home-manager via `nix run home-manager/master -- init --switch`

This PR fixes that

# Context
Fixes https://github.com/NixOS/nix/issues/8978.

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

2023-09-15 15:58 UTC, Hoverbear approved these changes
Tested this on an Ubuntu 22.04 VM by using `./nix-installer install --nix-package-url file:///home/ana/nix-2.18.0pre20230915_be60e2b-x86_64-linux.tar.xz` with a copy of `nix-installer` and the `hydraJobs.binaryTarball.x86_64-linux` today.

Seems to work well! I was a bit unsure about creating the file when you run `nix flake init` or `nix flake new`, but it seems fine.


### `nix run`

```bash
ana@ephemeral-ubuntu:~$ ./nix-installer install --nix-package-url file:///home/ana/nix-2.18.0pre20230915_be60e2b-x86_64-linux.tar.xz 
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
[sudo] password for ana: 
Nix install plan (v0.11.0)
Planner: linux

Configured settings:
* nix_package_url: "file:///home/ana/nix-2.18.0pre20230915_be60e2b-x86_64-linux.tar.xz"

Planned actions:
* Create directory `/nix`
* Fetch `file:///home/ana/nix-2.18.0pre20230915_be60e2b-x86_64-linux.tar.xz` to `/nix/temp-install-dir`
* Create a directory tree in `/nix`
* Move the downloaded Nix into `/nix`
* Create build group (GID 30000)
* Setup the default Nix profile
* Place the Nix configuration in `/etc/nix/nix.conf`
* Configure the shell profiles
* Configure Nix daemon related settings with systemd
* Remove directory `/nix/temp-install-dir`


Proceed? ([Y]es/[n]o/[e]xplain): y
 INFO Step: Create directory `/nix`
 INFO Step: Provision Nix
 INFO Step: Create build group (GID 30000)
 INFO Step: Configure Nix
 INFO Step: Create directory `/etc/tmpfiles.d`
 INFO Step: Configure Nix daemon related settings with systemd
 INFO Step: Remove directory `/nix/temp-install-dir`
Nix was installed successfully!
To get started using Nix, open a new shell or run `. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh`

ana@ephemeral-ubuntu:~$ . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
ana@ephemeral-ubuntu:~$ ls .local/state/nix/profiles
ls: cannot access '.local/state/nix/profiles': No such file or directory
ana@ephemeral-ubuntu:~$ nix run nixpkgs#hello
Hello, world!
ana@ephemeral-ubuntu:~$ ls .local/state/nix/
profiles
```

(For other commands, I removed `~/.local/state` and `~/.nix-profile` before testing)

### `nix shell`

```bash
ana@ephemeral-ubuntu:~$ ls .local/state/nix/
ls: cannot access '.local/state/nix/': No such file or directory
ana@ephemeral-ubuntu:~$ nix shell nixpkgs#hello
ana@ephemeral-ubuntu:~$ ls .local/state/nix/
profiles
```

### `nix develop`

```bash
ana@ephemeral-ubuntu:~$ ls .local/state/nix
ls: cannot access '.local/state/nix': No such file or directory
ana@ephemeral-ubuntu:~$ nix develop nixpkgs#hello
(nix:hello-2.12.1-env) ana@ephemeral-ubuntu:~$ ls .local/state/nix
profiles
(nix:hello-2.12.1-env) ana@ephemeral-ubuntu:~$ 
exit
```

### `nix flake init`

```bash
ana@ephemeral-ubuntu:~$ rm -rf .nix-profile 
ana@ephemeral-ubuntu:~$ rm -rf .local/state
ana@ephemeral-ubuntu:~$ nix flake init
wrote: /home/ana/flake.nix
ana@ephemeral-ubuntu:~$ ls .local/state/nix
profiles
```

### `nix flake new`

```bash
ana@ephemeral-ubuntu:~$ rm -rf .nix-profile 
ana@ephemeral-ubuntu:~$ rm -rf .local/state
ana@ephemeral-ubuntu:~$ nix flake new asd
wrote: /home/ana/asd/flake.nix
ana@ephemeral-ubuntu:~$ ls .local/state/nix
profiles
```

2023-09-15 17:31 UTC, e-nikolov commented
> I was a bit unsure about creating the file when you run nix flake init or nix flake new

My thinking was that if nix flake init/new don't create the profile, then some tools that use flakes might get errors if they were installed via another package manager or git clone prior to nix being installed.

Also I saw that in v2.13.3 nix flake init/new were creating the profile at the old location `/nix/var/nix/profiles/per-user`, so it seemed consistent with the old behviour.

2023-09-15 17:43 UTC, Ericson2314 requested changes
Not creating to dirs in 2.15 might have been accident, but I think it is a good change. Commands that do not have to do a profile should not touch that file; it is good to be stateless.

2023-09-15 18:30 UTC, Hoverbear commented
@Ericson2314 just to confirm you are requesting that the `nix flake init` and `nix flake new` commands not do this, but you approve of `shell`, `run`, and `develop` creating the directory?

2023-09-21 16:29 UTC, Ericson2314 commented
No I don't approve of any of those commands doing it. None of them have to do with the default profile.

2026-05-18 18:02 UTC, tomberek commented
stale: re-open and re-base as needed

2026-05-18 18:02 UTC, closed without merging