fetchTree: handle tarballs with multiple top-level files
NixOS/nix pull request #9053
Opened 2023-09-27 11:07 UTC by fgaz

# Motivation

See #7083. While the issue can be worked around by using the `file` type, it imposes a dependency on nixpkgs and makes implementation of other fetchers based on `downloadTarball` more difficult.

# Context

Issue #7083 suggests two solutions to this problem:

1. If there are multiple top-level files, use the archive root
2. A stripRoot attribute, like in nixpkgs' fetchzip

This patch implements (1). It is forward-compatible with (2) if a missing stripRoot is interpreted as "automatic".

Fixes #7083

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

2023-09-27 21:43 UTC, roberth requested changes
Needs a test in `tests/tarball.sh`

2023-10-16 11:39 UTC, edolstra commented
I'd prefer not to do this. The lazy-trees branch completely changes how tarballs are handled (they're imported into a local git cache and accessed from there), and it's not clear how to handle tarballs with more than one root object.

2023-10-25 14:21 UTC, fgaz commented
@edolstra Why isn't it clear? Is it because we don't know whether to [strip the root](https://github.com/NixOS/nix/pull/6530/files#diff-1cf3d4aeb3f1a65a47ae618b0f9f7328c9ebf648f915c15257b1ef103970c9b4R322) until all entries are processed?

2023-11-23 17:40 UTC, thufschmitt commented
> what about a stripRoot parameter?

@fgaz That seems to be a good solution (defaulting it to `true` and mentioning it in the error message if there's more than one toplevel dir)

2023-11-24 13:04 UTC, roberth commented
> and it's not clear how to handle tarballs with more than one root object.

libgit should make this quite easy. Assuming you want to have a streaming implementation, you stream all the contents into blobs, and keep all directory entries, in the original tarball layout at first (probably in memory, because maintaining such a data structure on disk would be inefficient - could be done though, don't care). At the end, you check whether the raw root contains a single directory. If it does, you return its contents instead of the root.
Note that in both tarball and zip you have to read at least the archive end to determine the raw root contents, so streaming is only about minimizing memory usage, not speeding up access.


> what about a stripRoot parameter?

I'm not so sure about that. Less "configuration" is generally better.

2023-11-24 14:02 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/2023-11-24-nix-team-meeting-minutes-106/35955/1

2024-03-23 09:23 UTC, pinpox commented
Are there any workarounds on how to handle zip flake inputs with mutiple files in the meantime?

2024-03-26 17:27 UTC, fgaz commented
@pinpox You could fetch as file and import from derivation.

---

#9485 was merged, so I guess this is unblocked?

> can do it even simpler, and always create a directory, and if that ends up only containing a directory, throw away the excess layer

2024-03-27 09:41 UTC, pinpox commented
> @pinpox You could fetch as file and import from derivation.

Hm, true, but has the downside of having to provide and update the hash myself instead of it being managed in `flake.lock`. I think this is still very relevant and an important feature.

2024-03-29 10:52 UTC, thufschmitt commented
> has the downside of having to provide and update the hash myself instead of it being managed in flake.lock

You can still have it as a flake input using the file [input type](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake#types)

2024-07-29 14:59 UTC, closed without merging