Fix error handling for open(2) on gc.lock
NixOS/nix pull request #9155
Opened 2023-10-14 12:14 UTC by kpcyrd

# Motivation

I tried to setup nix on Arch Linux and got this error:

```
% nix flake init
error: acquiring/releasing lock: Bad file descriptor
```

# Context

Using strace I saw this:

```
[pid 748007] openat(AT_FDCWD, "/nix/var/nix/gc.lock", O_RDWR|O_CREAT|O_CLOEXEC, 0600) = -1 EACCES (Permission denied)
[pid 748007] flock(-1, LOCK_SH|LOCK_NB) = -1 EBADF (Bad file descriptor)
```

This is a common error pattern in C, at this point I had a high suspicion the return value of `openat` is not being checked.

I cloned the repository and found this function with grep:

```c
AutoCloseFD LocalStore::openGCLock()
{
    Path fnGCLock = stateDir + "/gc.lock";
    auto fdGCLock = open(fnGCLock.c_str(), O_RDWR | O_CREAT | O_CLOEXEC, 0600);
    if (!fdGCLock)
        throw SysError("opening global GC lock '%1%'", fnGCLock);
    return fdGCLock;
}
```

I barely know anything about C++, but assuming this is `open(2)` from libc the documentation says:

```
RETURN VALUE
       On  success,  open(), openat(), and creat() return the new file descriptor (a nonnegative integer).  On er‐
       ror, -1 is returned and errno is set to indicate the error.
```

The current code is:
```c
    if (fdGCLock == 0)
        throw SysError("opening global GC lock '%1%'", fnGCLock);
```

I think this throw is essentially unreachable, 0 is a valid file descriptor but usually always already occupied by `stdin`.

Instead I think it should be:
```c
    if (fdGCLock == -1)
        throw SysError("opening global GC lock '%1%'", fnGCLock);
```

Note this patch is untested and I barely know what I'm doing.

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

2023-10-14 20:42 UTC, knedlsepp approved these changes
Great find! :clap: 
It seems the function `AutoCloseFD openFile(const Path & path)` also suffers from the same issue. https://github.com/NixOS/nix/blob/d070d8b7460f412a657745698dba291c66792402/src/libstore/binary-cache-store.cc#L124-L130 

That function seems to be dead code though. :thinking:

2023-10-14 20:42 UTC, knedlsepp commented on src/libstore/local-store.cc
>      auto fdGCLock = open(fnGCLock.c_str(), O_RDWR | O_CREAT | O_CLOEXEC, 0600);
An alternative could be to use `AutoCloseFD fdGCLock = open(...);` here instead, which will create a wrapper that will correctly compare the contained file descriptor to `-1` when implicitly converted to bool.
https://github.com/NixOS/nix/blob/d070d8b7460f412a657745698dba291c66792402/src/libutil/util.cc#L910-L913

This is used a couple of times around the codebase and maybe what was intended here.

2023-10-16 07:07 UTC, thufschmitt requested changes
Good catch, thanks :)

As @knedlsepp noticed, using an `AutoCloseFD` would be more consistent. Can you change it to that?

2026-05-18 19:13 UTC, tomberek commented
Fixed in https://github.com/NixOS/nix/pull/15858

2026-05-18 19:13 UTC, closed without merging