Fix transitive input locking.
NixOS/nix pull request #9173
Opened 2023-10-16 20:57 UTC by vkryachko

Fixes reproducibility issue described in #9143

# Motivation

Fixes #9143

# Context

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

2023-10-18 05:11 UTC, thufschmitt requested changes
Thanks, that looks good.

The whole resolution logic is a bit scary though. Can you add a test for it? Both to make sure that `.follows` now does the right thing and that `--override-input` still works

2023-10-18 05:11 UTC, thufschmitt commented on src/libexpr/flake/flake.cc
> +                    bool hasCliOverride = explicitCliOverrides.find(inputPath) != explicitCliOverrides.end();
(nit)

```suggestion
                    bool hasCliOverride = explicitCliOverrides.contains(inputPath);
```

2023-11-22 16:17 UTC, vkryachko commented
@thufschmitt friendly ping.

2023-11-23 07:54 UTC, thufschmitt approved these changes
Sorry for the delay! And thanks for the test. Looks good now

2023-11-23 07:54 UTC, merged