Move restricted/pure-eval access control out of the evaluator and into the accessor
NixOS/nix pull request #9497
Opened 2023-11-30 15:19 UTC by edolstra

# Motivation

Extracted from lazy-trees.

# Context

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

2023-11-30 16:43 UTC, Ericson2314 commented
Didn't read all the code while it is still draft, but the concept is quite nice!

2023-11-30 22:55 UTC, roberth requested changes
Symlinks strike again.
Otherwise looks like the right direction.

2023-11-30 22:55 UTC, roberth commented on src/libfetchers/filtering-input-accessor.hh
> + * access control policy.
```suggestion
 * control. Subclasses should override `isAllowed()` to implement an
 * access control policy. The error message is customized at construction.
```

2023-11-30 22:55 UTC, roberth commented on tests/functional/restricted.sh
> +nix-instantiate --restrict-eval --eval -E 'let __nixPath = [ { prefix = "foo"; path = ./.; } ]; in builtins.readFile <foo/simple.nix>' -I src=.
```suggestion
expect 1 nix-instantiate --restrict-eval --eval -E 'let __nixPath = [ { prefix = "foo"; path = ./.; } ]; in builtins.readFile <foo/simple.nix>' 2>&1 | grep "restricted"
nix-instantiate --restrict-eval --eval -E 'let __nixPath = [ { prefix = "foo"; path = ./.; } ]; in builtins.readFile <foo/simple.nix>' -I src=.
```

Make sure it's the right error.

2023-11-30 22:55 UTC, roberth commented on tests/functional/restricted.sh
We have a regression with symlinks. Needs a test case.
Currently:

```console
ls -l tunnel.d/
total 4
lrwxrwxrwx 1 user user 2 Nov 30 23:46 tunnel -> ..

$ ./result/bin/nix-instantiate --restrict-eval --eval -E 'let __nixPath = [ { prefix = "foo"; path = ./tunnel.d; } ]; in builtins.readFile <foo/tunnel/aliens-truth>' -I tunnel.d
"They're among us.\n"
```

2023-11-30 22:57 UTC, edolstra commented on src/libexpr/primops.cc
> +            // be rewritten to the actual output).
No, it's a moved comment.

2023-12-06 13:05 UTC, edolstra commented on tests/functional/restricted.sh
> +nix-instantiate --restrict-eval --eval -E 'let __nixPath = [ { prefix = "foo"; path = ./.; } ]; in builtins.readFile <foo/simple.nix>' -I src=.
Done.

2023-12-06 13:07 UTC, edolstra commented on src/libfetchers/filtering-input-accessor.hh
> + * forbidden.
No it should really say that it's required to throw `RestrictedPathError`.

2023-12-06 15:25 UTC, roberth commented on src/libfetchers/filtering-input-accessor.hh
> + * forbidden.
That's also ok, but then it should be 

```c++
typedef std::function<void(const CanonPath & path)> ThrowNotAllowedError;
```

2023-12-08 21:21 UTC, roberth approved these changes

2023-12-08 21:21 UTC, merged

2024-02-07 17:20 UTC, infinisil commented
This caused a regression: https://github.com/NixOS/nix/issues/9901